local cityName = GetConvar("cityName","Base")

local Garages = {
------------------ COMMUM -----------------------
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(55.44,-876.17,30.67,0.0),
            ["Positions"] = {
                [1] = vector4(44.15,-870.83,29.96,158.75),
                [2] = vector4(47.39,-872.14,29.94,158.75),
                [3] = vector4(50.73,-873.4,29.93,158.75),
                [4] = vector4(44.15,-870.83,29.96,158.75),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(599.04,2745.33,42.04,0.0),
            ["Positions"] = {
                [1] = vector4(598.63,2737.85,41.69,184.26),
                [2] = vector4(595.59,2737.55,41.7,184.26),
                [3] = vector4(601.75,2738.08,41.65,184.26),
                [4] = vector4(604.82,2738.27,41.64,187.09),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-136.8,6356.84,31.49,0.0),
            ["Positions"] = {
                [1] = vector4(-136.1,6346.53,31.16,42.52),
                [2] = vector4(-133.72,6349.01,31.16,42.52),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(275.23,-345.56,45.17,0.0),
            ["Positions"] = {
                [1] = vector4(280.82,-330.06,44.42,68.04),
                [2] = vector4(278.5,-336.84,44.42,68.04),
                [3] = vector4(265.77,-331.89,44.42,252.29),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(596.43,90.68,93.13,0.0),
            ["Positions"] = {
                [1] = vector4(598.69,98.42,92.57,249.45),
                [2] = vector4(599.82,102.03,92.57,249.45),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-340.57,266.04,85.68,0.0),
            ["Positions"] = {
                [1] = vector4(-332.5,284.8,85.93,2.84),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-2030.03,-465.99,11.59,0.0),
            ["Positions"] = {
                [1] = vector4(-2037.4,-461.02,11.07,138.9),
                [2] = vector4(-2039.78,-459.07,11.07,138.9),
                [3] = vector4(-2042.12,-457.1,11.07,138.9),
                [4] = vector4(-2044.47,-455.11,11.07,138.9),
                [5] = vector4(-2046.85,-453.09,11.07,138.9),
                [6] = vector4(-2049.12,-451.17,11.07,138.9),
                [7] = vector4(-2051.51,-449.23,11.07,138.9),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-1184.94,-1509.99,4.65,0.0),
            ["Positions"] = {
                [1] = vector4(-1186.87,-1490.71,4.04,121.89),
                [2] = vector4(-1188.69,-1488.27,4.04,121.89),
                [3] = vector4(-1185.23,-1493.28,4.04,121.89),
                [4] = vector4(-1183.29,-1495.81,4.04,121.89),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(213.97,-808.43,31.0,0.0),
            ["Positions"] = {
                [1] = vector4(223.92,-799.2,30.33,249.45),
                [2] = vector4(224.85,-796.69,30.33,249.45),
                [3] = vector4(222.9,-801.61,30.33,249.45),
                [4] = vector4(221.93,-804.11,30.35,249.45),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-348.89,-874.02,31.31,0.0),
            ["Positions"] = {
                [1] = vector4(-336.35,-876.98,30.75,167.25),
                [2] = vector4(-332.72,-877.71,30.75,167.25),
                [3] = vector4(-339.98,-876.27,30.75,167.25),
                [4] = vector4(-343.62,-875.51,30.75,167.25),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(67.72,12.3,69.22,0.0),
            ["Positions"] = {
                [1] = vector4(57.76,18.76,69.03,340.16),
                [2] = vector4(54.8,19.92,69.25,340.16),
                [3] = vector4(60.78,17.6,68.92,340.16),
                [4] = vector4(63.87,16.5,68.87,340.16),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(361.96,297.8,103.88,0.0),
            ["Positions"] = {
                [1] = vector4(360.68,293.83,103.51,249.45),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(1035.84,-763.87,58.0,0.0),
            ["Positions"] = {
                [1] = vector4(1046.55,-782.0,57.68,90.71),
                [2] = vector4(1046.54,-785.65,57.66,90.71),
                [3] = vector4(1046.56,-778.24,57.68,90.71),
                [4] = vector4(1046.56,-774.55,57.69,90.71),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-796.69,-2022.85,9.17,0.0),
            ["Positions"] = {
                [1] = vector4(-774.92,-2044.9,8.56,314.65),
                [2] = vector4(-777.36,-2042.58,8.56,314.65),
                [3] = vector4(-779.77,-2040.03,8.56,314.65),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(453.28,-1146.77,29.5,0.0),
            ["Positions"] = {
                [1] = vector4(467.1,-1157.73,28.96,87.88),
                [2] = vector4(467.16,-1154.75,28.96,85.04),
                [3] = vector4(467.33,-1151.89,28.96,85.04),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(528.65,-146.25,58.37,0.0),
            ["Positions"] = {
                [1] = vector4(548.83,-136.31,59.01,181.42),
                [2] = vector4(552.81,-136.41,58.99,178.59),
                [3] = vector4(544.84,-136.25,59.01,178.59),
                [4] = vector4(540.99,-136.2,59.13,178.59),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-1159.56,-739.39,19.88,0.0),
            ["Positions"] = {
                [1] = vector4(-1144.95,-745.49,19.34,104.89),
                [2] = vector4(-1142.76,-748.44,19.19,107.72),
                [3] = vector4(-1140.18,-751.41,19.06,107.72),
                [4] = vector4(-1137.99,-754.36,18.91,107.72),
                [5] = vector4(-1135.43,-757.3,18.75,107.72),
                [6] = vector4(-1133.12,-760.4,18.59,107.72),
                [7] = vector4(-1130.59,-763.27,18.43,107.72),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(101.23,-1073.64,29.37,0.0),
            ["Positions"] = {
                [1] = vector4(108.88,-1056.23,28.88,246.62),
                [2] = vector4(110.27,-1052.86,28.88,246.62),
                [3] = vector4(107.42,-1059.61,28.88,246.62),
                [4] = vector4(105.9,-1063.14,28.88,246.62),
            },
        },
    },
------------------ BOATS ------------------------
    {
        ["Info"] = {
            ["Name"] = "Boats",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(1298.77,4216.51,33.9,0.0),
            ["Positions"] = {
                [1] = vector4(1288.54,4228.66,31.78,164.41),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Boats",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-800.58,-1494.38,1.58,0.0),
            ["Positions"] = {
                [1] = vector4(-807.23,-1506.13,0.74,104.89),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Boats",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(4948.88,-5154.06,2.46,0.0),
            ["Positions"] = {
                [1] = vector4(4928.8,-5152.91,0.72,65.2),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Boats",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-1600.93,-1141.16,2.14,133.23),
            ["Positions"] = {
                [1] = vector4(-1639.09,-1176.31,1.7,133.23),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Boats",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-462.68,6456.45,2.88,36.86),
            ["Positions"] = {
                [1] = vector4(-504.55,6481.85,0.62,34.02),
            },
        },
        ["Ped"] = {
            ["Distance"] = 100,
            ["Model"] = "s_m_y_baywatch_01",
            ["Anim"] = { "amb@code_human_wander_idles_cop@female@static","static" }
        },
    },
------------------ POLICE -----------------------
    {
        ["Info"] = {
            ["Name"] = "Police-1",
            ["Payment"] = false,
            ["Perm"] = "Policia",
            ["Level"] = "1",
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-938.0,-2076.15,9.3,226.78),
            ["Positions"] = {
                [1] = vector4(-940.53,-2079.21,8.68,226.78),
                [2] = vector4(-942.96,-2081.61,8.68,226.78),
                [3] = vector4(-945.37,-2084.13,8.68,226.78),
                [4] = vector4(-947.67,-2086.65,8.68,226.78),
                [5] = vector4(-950.16,-2089.09,8.68,226.78),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Police-2",
            ["Payment"] = false,
            ["Perm"] = "Policia",
            ["Level"] = "2",
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-915.53,-2053.59,9.3,226.78),
            ["Positions"] = {
                [1] = vector4(-911.78,-2050.73,8.68,226.78),
                [2] = vector4(-909.29,-2048.18,8.66,226.78),
                [3] = vector4(-906.96,-2045.76,8.66,226.78),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Police-3",
            ["Payment"] = false,
            ["Perm"] = "Policia",
            ["Level"] = "3",
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-894.85,-2032.91,9.3,226.78),
            ["Positions"] = {
                [1] = vector4(-897.13,-2035.89,8.66,226.78),
                [2] = vector4(-899.56,-2038.33,8.66,226.78),
                [3] = vector4(-902.0,-2040.81,8.66,226.78),
                [4] = vector4(-904.49,-2043.28,8.66,226.78),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Police-Util",
            ["Payment"] = false,
            ["Perm"] = "Policia",
            ["Level"] = "4",
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-970.35,-2062.66,9.4,226.78),
            ["Positions"] = {
                [1] = vector4(-980.04,-2057.61,9.03,226.78),
                [2] = vector4(-982.93,-2061.36,9.03,226.78),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Police-Heli",
            ["Payment"] = false,
            ["Perm"] = "Policia",
            ["Level"] = "4",
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-943.79,-2022.68,11.32,226.78),
            ["Positions"] = {
                [1] = vector4(-951.09,-2021.06,11.69,226.78),
            },
        },
    },
------------------ PARAMEDIC --------------------
    {
        ["Info"] = {
            ["Name"] = "Paramedic-1",
            ["Payment"] = false,
            ["Perm"] = "Paramedic",
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(1116.56,-1509.16,34.85,294.81),
            ["Positions"] = {
                [1] = vector4(1116.9,-1505.86,34.47,272.13),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Paramedic-Heli",
            ["Payment"] = false,
            ["Perm"] = "Paramedic",
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(1180.38,-1533.2,39.39,272.13),
            ["Positions"] = {
                [1] = vector4(1180.58,-1542.18,39.39,269.3),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(1157.28,-1486.56,34.85,5.67),
            ["Positions"] = {
                [1] = vector4(1156.05,-1477.87,34.07,87.88),
                [2] = vector4(1155.95,-1474.16,34.07,87.88),
                [3] = vector4(1155.78,-1470.59,34.07,87.88),
            },
        },
    },
------------------ MECHANIC ---------------------
    {
        ["Info"] = {
            ["Name"] = "Mechanic-1",
            ["Payment"] = false,
            ["Perm"] = "Mechanic",
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(856.58,-2132.07,30.53,90.71),
            ["Positions"] = {
                [1] = vector4(848.73,-2130.39,29.91,269.3),
                [2] = vector4(848.93,-2126.82,29.91,269.3),
                [3] = vector4(849.34,-2123.38,29.91,269.3),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Mechanic-Heli",
            ["Payment"] = false,
            ["Perm"] = "Mechanic",
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(868.16,-2183.55,30.48,175.75),
            ["Positions"] = {
                [1] = vector4(877.67,-2185.09,30.89,170.08),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Garage",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(852.95,-2095.37,30.53,263.63),
            ["Positions"] = {
                [1] = vector4(850.71,-2098.41,30.21,266.46),
                [2] = vector4(850.13,-2101.81,30.19,266.46),
                [3] = vector4(849.66,-2105.39,30.21,269.3),
            },
        },
    },
------------------- JOBS ------------------------
    {
        ["Info"] = {
            ["Name"] = "Tractor",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(752.73,6468.2,30.57,87.88),
            ["Positions"] = {
                [1] = vector4(747.74,6472.63,28.81,82.21),
            },
        },
        ["Ped"] = {
            ["Distance"] = 100,
            ["Model"] = "cs_old_man2",
            ["anim"] = { "anim@heists@heist_corona@single_team","single_team_loop_boss" }
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Driver",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(453.74,-600.6,28.59,0.0),
            ["Positions"] = {
                [1] = vector4(460.98,-619.81,28.49,215.44),
                [2] = vector4(461.54,-612.34,28.49,215.44),
                [3] = vector4(462.81,-606.03,28.49,212.6),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Lumberman",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(2434.96,5012.06,46.84,0.0),
            ["Positions"] = {
                [1] = vector4(2441.6,5010.56,45.76,277.8),
            },
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Seara",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-22.77,6316.92,31.37,308.98),
            ["Positions"] = {
                [1] = vector4(-18.44,6321.82,31.22,215.44),
            },
        },
        ["Ped"] = {
            ["Distance"] = 100,
            ["Model"] = "s_m_y_valet_01",
            ["anim"] = { "anim@heists@heist_corona@single_team","single_team_loop_boss" }
        },
    },
    {
        ["Info"] = {
            ["Name"] = "Sedex",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-396.32,6156.28,31.48,5.67),
            ["Positions"] = {
                [1] = vector4(-399.91,6163.68,31.48,345.83),
            },
        },
        ["Ped"] = {
            ["Distance"] = 100,
            ["Model"] = "s_m_y_valet_01",
            ["anim"] = { "anim@heists@heist_corona@single_team","single_team_loop_boss" }
        },
    },
------------------- OTHERS ----------------------
    {
        ["Info"] = {
            ["Name"] = "Kart",
            ["Payment"] = false,
            ["Perm"] = nil,
            ["Level"] = nil,
        },
        ["Teleport"] = true,
        ["Spawns"] = {
            ["Open"] = vector4(-161.11,-2145.49,16.7,102.05),
            ["Positions"] = {
                [1] = vector4(-160.7,-2141.84,15.84,291.97),
                [2] = vector4(-162.29,-2138.46,15.84,291.97),
                [3] = vector4(-163.29,-2135.03,15.84,291.97),
            },
        },
    },
}

local CityConfig = {
    ["Base"] = function()
        -- Locations[#Locations+1] = {
        --     ["Info"] = {
        --         ["Name"] = "", -- Nome (vip,Garage,etc)
        --         ["Payment"] = false, -- Paga para usar ou nao
        --         ["Perm"] = "", -- Permissao para usar
        --         ["Level"] = "", -- Nivel para usar
        --     },
        --     ["Spawns"] = {
        --         ["Open"] = vector4(), -- Posicao para abrir o menu
        --         ["Positions"] = {
        --             [1] = vector4(), -- Posicao para spawnar
        --         },
        --     },
        --     ["Ped"] = {
        --         ["Distance"] = 50, -- Distancia para aparecer o ped
        --         ["Model"] = "", -- Model do ped
        --         ["Custom"] = { -- Customizacao do ped
        --             ["Face"] = "", -- Face do ped
        --             ["Clothes"] = "", -- Roupas do ped
        --         },
        --         ["Anim"] = { "","" } -- Animacao do ped
        --     },
        -- }
    end
}

local GarageVips = {
    [1] = {
        [5] = {
            "hakuchou",
            "mule"
        },
        [4] = {
            "hakuchou",
            "benson"
        },
        [3] = {
            "hakuchou",
            "benson",
            "xls2"
        },
        [2] = {
            "xls2",
            "maverick",
            "hakuchou",
            "benson",
            "pounder"
        },
        [1] = {
            "xls2",
            "volatus",
            "hakuchou",
            "benson",
            "pounder",
            "rentalbus"
        }
    },
    [2] = {
        [5] = {
            "double",
            "mule"
        },
        [4] = {
            "double",
            "mule"
        },
        [3] = {
            "double",
            "benson",
            "landstalker2"
        },
        [2] = {
            "landstalker2",
            "benson",
            "double",
            "mule2",
            "seasparrow2"
        },
        [1] = {
            "landstalker2",
            "pounder",
            "double",
            "benson",
            "buzzard2"
        }
    },
    [3] = {
        [5] = {
            "sanchez2",
            "mule"
        },
        [4] = {
            "sanchez2",
            "mule"
        },
        [3] = {
            "sanchez2",
            "mule"
        },
        [2] = {
            "sanchez2",
            "mule",
            "mesa"
        },
        [1] = {
            "sanchez2",
            "mule",
            "mesa"
        }
    }
}

local GarageWorks = {
------------------ BOATS ------------------------
    ["Boats"] = {
		"seashark",
		"dinghy",
        "tug",
	},
------------------ POLICE -----------------------
    ["Police-1"] = {
		"blazerpm",
		"blazerrota",
		"blazerft",
		"blazerbaep",
	},
    ["Police-2"] = {
		"dustercivil",
		"golcivil",
		"paliocivil",
		"spincivil",
	},
    ["Police-3"] = {
		"dusterpmesp",
		"golpm",
		"paliopm1",
		"spinpm",
        "xtrocam",
        "xre2019pm1",
	},
    ["Police-Util"] = {
		"riot",
		"pbus",
		"riot2",
        "barracks3",
        "pbus",
        "onipc1",
	},
    ["Police-Heli"] = {
		"polas350",
		"as350",
		"hger",
	},
------------------ PARAMEDIC --------------------
	["Paramedic-1"] = {
		"ambulancia",
		"hpmoto",
		"merchospital"
	},
	["Paramedic-Heli"] = {
		"as350samu"
	},
------------------ MECHANIC ---------------------
	["Mechanic-1"] = {
		"Fcb500mecK",
		"rs62"
	},
    ["Mechanic-Heli"] = {
		"FhelimecK"
	},
------------------- JOBS ------------------------
    ["Tractor"] = {
		"tractor2"
	},
	["Driver"] = {
		"onibussanta"
	},
	["Lumberman"] = {
		"ratloader"
	},
    ["Seara"] = {
		"sprinter2112"
	},
    ["Sedex"] = {
		"sprinter211"
	},
------------------- OTHERS ----------------------
    ["Kart"] = {
		"veto",
		"veto2",
	},
}

local VehicleTypes = {
    ["stunt"] = "plane",
    ["avisa"] = "trailer",
    ["argiu"] = "automobile",
    ["ninef"] = "automobile",
    ["supervolito"] = "heli",
    ["armytrailer2"] = "trailer",
    ["buffalo2"] = "automobile",
    ["rs62"] = "automobile",
    ["thrax"] = "automobile",
    ["riot"] = "automobile",
    ["ninef2"] = "automobile",
    ["babygs63"] = "automobile",
    ["blazer2"] = "quadbike",
    ["jester"] = "automobile",
    ["blista"] = "automobile",
    ["kostoblindado"] = "automobile",
    ["fgols3"] = "automobile",
    ["asea"] = "automobile",
    ["tornado4"] = "automobile",
    ["asea2"] = "automobile",
    ["armytanker"] = "trailer",
    ["mazdarx72"] = "automobile",
    ["barracks3"] = "automobile",
    ["z190"] = "automobile",
    ["dilettante2"] = "automobile",
    ["verus"] = "quadbike",
    ["cheetah2"] = "automobile",
    ["issi6"] = "automobile",
    ["rmodcharger69"] = "automobile",
    ["cogcabrio"] = "automobile",
    ["turismor"] = "automobile",
    ["trail22rota"] = "automobile",
    ["revolter"] = "automobile",
    ["bus"] = "automobile",
    ["flatbed"] = "automobile",
    ["mantgabox"] = "automobile",
    ["boattrailer"] = "trailer",
    ["pistaspider19"] = "automobile",
    ["ambulance"] = "automobile",
    ["buffalo"] = "automobile",
    ["benson"] = "automobile",
    ["porscheag"] = "automobile",
    ["armytrailer"] = "trailer",
    ["freighttrailer"] = "trailer",
    ["celta"] = "automobile",
    ["bullet"] = "automobile",
    ["vwtouareg"] = "automobile",
    ["dc5"] = "automobile",
    ["trail22rotacmd"] = "automobile",
    ["hiluxbaep"] = "automobile",
    ["boxville2"] = "automobile",
    ["rrexclusivo"] = "automobile",
    ["coach"] = "automobile",
    ["bati"] = "bike",
    ["blazer"] = "quadbike",
    ["boor"] = "automobile",
    ["btype3"] = "automobile",
    ["stratum"] = "automobile",
    ["ff450meck"] = "automobile",
    ["20xmax"] = "bike",
    ["slamvan2"] = "automobile",
    ["airbus"] = "automobile",
    ["massacro"] = "automobile",
    ["z419"] = "automobile",
    ["cuban800"] = "plane",
    ["cherokee2"] = "automobile",
    ["bm422pxx2ncs"] = "automobile",
    ["toro2"] = "boat",
    ["bmwm5e3495"] = "automobile",
    ["hyundson2016"] = "automobile",
    ["burrito4"] = "automobile",
    ["novak"] = "automobile",
    ["tanker2"] = "trailer",
    ["asterope"] = "automobile",
    ["glendale"] = "automobile",
    ["airtug"] = "automobile",
    ["caracara2"] = "automobile",
    ["barracks"] = "automobile",
    ["babym4c"] = "automobile",
    ["gresley"] = "automobile",
    ["handler"] = "automobile",
    ["cavalcade"] = "automobile",
    ["towtruck2"] = "automobile",
    ["barracks2"] = "automobile",
    ["romero"] = "automobile",
    ["innovation"] = "bike",
    ["rvtoysupmk4"] = "automobile",
    ["chevimpala1967"] = "automobile",
    ["bjxl"] = "automobile",
    ["baller"] = "automobile",
    ["voltic"] = "automobile",
    ["pony"] = "automobile",
    ["baller2"] = "automobile",
    ["750li"] = "automobile",
    ["docktug"] = "automobile",
    ["banshee"] = "automobile",
    ["brickade"] = "automobile",
    ["longfin"] = "boat",
    ["f150army"] = "automobile",
    ["rvbnr34b"] = "automobile",
    ["cargoplane"] = "plane",
    ["winky"] = "automobile",
    ["felon2"] = "automobile",
    ["bfinjection"] = "automobile",
    ["subwrx"] = "automobile",
    ["nightshark"] = "automobile",
    ["biff"] = "automobile",
    ["voltic2"] = "automobile",
    ["terzo"] = "automobile",
    ["blazer3"] = "quadbike",
    ["mta"] = "automobile",
    ["velum2"] = "plane",
    ["burrito2"] = "automobile",
    ["barrage"] = "automobile",
    ["bison"] = "automobile",
    ["bison2"] = "automobile",
    ["bison3"] = "automobile",
    ["tyrant"] = "automobile",
    ["caddy2"] = "automobile",
    ["caddy"] = "automobile",
    ["cavalcade2"] = "automobile",
    ["skyliner34pol"] = "automobile",
    ["boxville"] = "automobile",
    ["seminole"] = "automobile",
    ["boxville3"] = "automobile",
    ["zeno"] = "automobile",
    ["bobcatxl"] = "automobile",
    ["comet2"] = "automobile",
    ["bodhi2"] = "automobile",
    ["buccaneer"] = "automobile",
    ["blimp2"] = "trailer",
    ["bulldozer"] = "automobile",
    ["hauler2"] = "automobile",
    ["vigilante"] = "automobile",
    ["rmodspeed"] = "automobile",
    ["blimp"] = "trailer",
    ["golcivil"] = "automobile",
    ["yfef12t"] = "automobile",
    ["gtrp"] = "automobile",
    ["zentorno"] = "automobile",
    ["burrito"] = "automobile",
    ["camper"] = "automobile",
    ["bmwz4me86coupe"] = "automobile",
    ["cheetah"] = "automobile",
    ["speeder2"] = "boat",
    ["clique"] = "automobile",
    ["burrito3"] = "automobile",
    ["wolfsbane"] = "bike",
    ["dilettante"] = "automobile",
    ["scrap"] = "automobile",
    ["exemplar"] = "automobile",
    ["burrito5"] = "automobile",
    ["fuscaleo"] = "automobile",
    ["subarung"] = "automobile",
    ["srt05e"] = "automobile",
    ["astmarlagonda"] = "automobile",
    ["manana"] = "automobile",
    ["komoda"] = "automobile",
    ["mule3"] = "automobile",
    ["policet"] = "automobile",
    ["tornado"] = "automobile",
    ["tyrus"] = "automobile",
    ["hexer"] = "bike",
    ["m2f22"] = "automobile",
    ["tampa3"] = "automobile",
    ["gburrito"] = "automobile",
    ["cablecar"] = "train",
    ["deluxokid"] = "automobile",
    ["ruffian"] = "bike",
    ["s1000rr"] = "bike",
    ["fq2"] = "automobile",
    ["omnisegt"] = "automobile",
    ["carbonizzare"] = "automobile",
    ["coquette"] = "automobile",
    ["tiptruck"] = "automobile",
    ["docktrailer"] = "trailer",
    ["phantom"] = "automobile",
    ["cutter"] = "automobile",
    ["futo"] = "automobile",
    ["dune"] = "automobile",
    ["dune2"] = "automobile",
    ["e300"] = "automobile",
    ["faggio3"] = "bike",
    ["mcgts"] = "automobile",
    ["predator"] = "boat",
    ["fusilade"] = "automobile",
    ["f60"] = "automobile",
    ["hotknife"] = "automobile",
    ["tribike3"] = "bicycle",
    ["dloader"] = "automobile",
    ["hustler"] = "automobile",
    ["vigero"] = "automobile",
    ["dubsta"] = "automobile",
    ["ruiner2"] = "automobile",
    ["vigero2"] = "automobile",
    ["dubsta2"] = "automobile",
    ["slamvan3"] = "automobile",
    ["draugur"] = "automobile",
    ["dump"] = "automobile",
    ["alphaz1"] = "plane",
    ["everon2"] = "automobile",
    ["basepm"] = "automobile",
    ["audirs5"] = "automobile",
    ["rubble"] = "automobile",
    ["slamvan6"] = "automobile",
    ["dominator"] = "automobile",
    ["fixter"] = "bicycle",
    ["nissangtr2"] = "automobile",
    ["emperor"] = "automobile",
    ["veto"] = "automobile",
    ["habanero"] = "automobile",
    ["emperor2"] = "automobile",
    ["mcf1"] = "automobile",
    ["keyrus"] = "automobile",
    ["emperor3"] = "automobile",
    ["shamal"] = "plane",
    ["brutus3"] = "automobile",
    ["tornado3"] = "automobile",
    ["silvia"] = "automobile",
    ["entityxf"] = "automobile",
    ["elegy2"] = "automobile",
    ["sharkm4"] = "automobile",
    ["tvtrailer"] = "trailer",
    ["peyote"] = "automobile",
    ["f620"] = "automobile",
    ["rt3000"] = "automobile",
    ["sky2000gtr"] = "automobile",
    ["picador"] = "automobile",
    ["fbi"] = "automobile",
    ["tampa"] = "automobile",
    ["gronos6x6"] = "automobile",
    ["thrust"] = "bike",
    ["fbi2"] = "automobile",
    ["stingergt"] = "automobile",
    ["felon"] = "automobile",
    ["buffalo3"] = "automobile",
    ["seashark3"] = "boat",
    ["sandking"] = "automobile",
    ["feltzer2"] = "automobile",
    ["pruf"] = "automobile",
    ["firetruk"] = "automobile",
    ["forklift"] = "automobile",
    ["fugitive"] = "automobile",
    ["tr4"] = "trailer",
    ["granger"] = "automobile",
    ["shinobi"] = "bike",
    ["adder"] = "automobile",
    ["gauntlet"] = "automobile",
    ["corsita"] = "automobile",
    ["caddy3"] = "automobile",
    ["hauler"] = "automobile",
    ["freightcont1"] = "train",
    ["infernus"] = "automobile",
    ["retinue2"] = "automobile",
    ["ingot"] = "automobile",
    ["haitun"] = "heli",
    ["tr2"] = "trailer",
    ["policiatahoe"] = "automobile",
    ["16santafe"] = "automobile",
    ["felon12"] = "automobile",
    ["scorcher"] = "bicycle",
    ["intruder"] = "automobile",
    ["issi2"] = "automobile",
    ["er34"] = "automobile",
    ["surge"] = "automobile",
    ["ztype"] = "automobile",
    ["visione"] = "automobile",
    ["stretch"] = "automobile",
    ["jackal"] = "automobile",
    ["journey"] = "automobile",
    ["khilux"] = "automobile",
    ["panthere"] = "automobile",
    ["jb700"] = "automobile",
    ["carbonrs"] = "bike",
    ["khamelion"] = "automobile",
    ["jester4"] = "automobile",
    ["phantom3"] = "automobile",
    ["issi4"] = "automobile",
    ["landstalker"] = "automobile",
    ["suntrap"] = "boat",
    ["raiden"] = "automobile",
    ["mclarenp1"] = "automobile",
    ["lguard"] = "automobile",
    ["luxor"] = "plane",
    ["mesa"] = "automobile",
    ["issi5"] = "automobile",
    ["swift"] = "heli",
    ["gtrcw"] = "automobile",
    ["db11"] = "automobile",
    ["mrbeanmini"] = "automobile",
    ["mesa2"] = "automobile",
    ["mesa3"] = "automobile",
    ["manana2"] = "automobile",
    ["policiataurus"] = "automobile",
    ["crusader"] = "automobile",
    ["trail21dpm"] = "automobile",
    ["minivan"] = "automobile",
    ["mixer"] = "automobile",
    ["trail17ft"] = "automobile",
    ["xfrs"] = "automobile",
    ["mixer2"] = "automobile",
    ["6x6urus"] = "automobile",
    ["monroe"] = "automobile",
    ["rebel"] = "automobile",
    ["mower"] = "automobile",
    ["mule"] = "automobile",
    ["faction"] = "automobile",
    ["pounder2"] = "automobile",
    ["rmodf40"] = "automobile",
    ["monster"] = "automobile",
    ["mule2"] = "automobile",
    ["sanchez"] = "bike",
    ["2017chiron"] = "automobile",
    ["oracle"] = "automobile",
    ["r33n"] = "automobile",
    ["vxr"] = "automobile",
    ["oracle2"] = "automobile",
    ["packer"] = "automobile",
    ["blazer5"] = "quadbike",
    ["patriot"] = "automobile",

    ["sabregt2"] = "automobile",
    ["brioso2"] = "automobile",
    ["pbus"] = "automobile",
    ["patrolboat"] = "boat",
    ["tornado2"] = "automobile",
    ["rmodbugatti"] = "automobile",
    ["cruiser"] = "bicycle",
    ["sadler2"] = "automobile",
    ["penumbra"] = "automobile",
    ["a45"] = "automobile",
    ["phoenix"] = "automobile",
    ["pounder"] = "automobile",
    ["savage"] = "heli",
    ["freightgrain"] = "train",
    ["trflat"] = "trailer",
    ["bbdawn"] = "automobile",
    ["verlierer2"] = "automobile",
    ["veneno"] = "automobile",
    ["police"] = "automobile",
    ["maverick"] = "heli",
    ["police4"] = "automobile",
    ["sultanrs"] = "automobile",
    ["police2"] = "automobile",
    ["sheava"] = "automobile",
    ["police3"] = "automobile",
    ["policeold1"] = "automobile",
    ["torero"] = "automobile",
    ["accord20"] = "automobile",
    ["ctsv16"] = "automobile",
    ["policeold2"] = "automobile",
    ["tigon"] = "automobile",
    ["22m5"] = "automobile",
    ["pony2"] = "automobile",
    ["virgo3"] = "automobile",
    ["legochiron"] = "automobile",
    ["prairie"] = "automobile",
    ["ratloader2"] = "automobile",
    ["pranger"] = "automobile",
    ["premier"] = "automobile",
    ["regina"] = "automobile",
    ["seasparrow3"] = "heli",
    ["trail21rota"] = "automobile",
    ["primo"] = "automobile",
    ["proptrailer"] = "trailer",
    ["nero"] = "automobile",
    ["babyas350"] = "heli",
    ["trailers"] = "trailer",
    ["rancherxl"] = "automobile",
    ["ram2500"] = "automobile",
    ["contender"] = "automobile",
    ["rancherxl2"] = "automobile",
    ["63lb"] = "automobile",
    ["kbati"] = "bike",
    ["razor"] = "automobile",
    ["c63"] = "automobile",
    ["flashgt"] = "automobile",
    ["towtruck"] = "automobile",
    ["rapidgt"] = "automobile",
    ["trailsamu"] = "automobile",
    ["baletrailer"] = "trailer",
    ["rapidgt2"] = "automobile",
    ["trailerlogs"] = "trailer",
    ["f82duke"] = "automobile",
    ["bnr34"] = "automobile",
    ["radi"] = "automobile",
    ["cargobob3"] = "heli",
    ["taipan"] = "automobile",
    ["deveste"] = "automobile",
    ["ratloader"] = "automobile",
    ["rmodbacalar"] = "automobile",
    ["miljet"] = "plane",
    ["rebel2"] = "automobile",
    ["rx7veilside"] = "automobile",
    ["rentalbus"] = "automobile",
    ["ruiner"] = "automobile",
    ["cerberus2"] = "automobile",
    ["rumpo"] = "automobile",
    ["rumpo2"] = "automobile",
    ["civic16"] = "automobile",
    ["youga2"] = "automobile",
    ["alpha"] = "automobile",
    ["rhino"] = "automobile",
    ["yacht3b"] = "boat",
    ["ripley"] = "automobile",
    ["mazdarx7"] = "automobile",
    ["schafter4"] = "automobile",
    ["babyr8"] = "automobile",
    ["voodoo2"] = "automobile",
    ["rocoto"] = "automobile",
    ["submersible"] = "trailer",
    ["schlagen"] = "automobile",
    ["bruiser3"] = "automobile",
    ["sabregt"] = "automobile",
    ["raroevo16"] = "automobile",
    ["kcarbonrs"] = "bike",
    ["bmwg07"] = "automobile",
    ["sadler"] = "automobile",
    ["xt660vip"] = "bike",
    ["cerberus3"] = "automobile",
    ["chevopalgran"] = "automobile",
    ["sandking2"] = "automobile",
    ["freight"] = "train",
    ["schafter2"] = "automobile",
    ["vagrant"] = "automobile",
    ["coquette3"] = "automobile",
    ["schwarzer"] = "automobile",
    ["lynx"] = "automobile",
    ["sentinel"] = "automobile",
    ["a110"] = "automobile",
    ["buzzard"] = "heli",
    ["patriot3"] = "automobile",
    ["sw4ft"] = "automobile",
    ["sentinel2"] = "automobile",
    ["dchallenger15"] = "automobile",
    ["taxi"] = "automobile",
    ["zion"] = "automobile",
    ["tractor2"] = "automobile",
    ["oycdefender"] = "automobile",
    ["outlaw"] = "automobile",
    ["zion2"] = "automobile",
    ["cbferrariitalia"] = "automobile",
    ["annihilator2"] = "heli",
    ["lx2018"] = "automobile",
    ["serrano"] = "automobile",
    ["sheriff"] = "automobile",
    ["sc1"] = "automobile",
    ["sheriff2"] = "automobile",
    ["raptorsound"] = "automobile",
    ["cblazer"] = "automobile",
    ["comet7"] = "automobile",
    ["xj6"] = "bike",
    ["speedo"] = "automobile",
    ["speedo2"] = "automobile",
    ["stanier"] = "automobile",
    ["180326"] = "automobile",
    ["superd"] = "automobile",
    ["stinger"] = "automobile",
    ["ttrs"] = "automobile",
    ["stockade"] = "automobile",
    ["impaler2"] = "automobile",
    ["technical"] = "automobile",
    ["stockade3"] = "automobile",
    ["h9gq"] = "automobile",
    ["elegy"] = "automobile",
    ["sultan"] = "automobile",
    ["surano"] = "automobile",
    ["surfer"] = "automobile",
    ["surfer2"] = "automobile",
    ["trail22pmespcmd"] = "automobile",
    ["taco"] = "automobile",
    ["gargoyle"] = "bike",
    ["tailgater"] = "automobile",
    ["manchez2"] = "bike",
    ["jeepcherokee"] = "automobile",
    ["tr3"] = "trailer",
    ["trash"] = "automobile",
    ["tractor"] = "automobile",
    ["rapidgt3"] = "automobile",
    ["tractor3"] = "automobile",
    ["graintrailer"] = "trailer",
    ["astonmartindbs"] = "automobile",
    ["tiptruck2"] = "automobile",
    ["tulip2"] = "automobile",
    ["tourbus"] = "automobile",
    ["imsa90"] = "automobile",
    ["oppressor"] = "bike",
    ["seashark"] = "boat",
    ["ambiental"] = "automobile",
    ["utillitruck"] = "automobile",
    ["utillitruck2"] = "automobile",
    ["utillitruck3"] = "automobile",
    ["chernobog"] = "automobile",
    ["slamvan"] = "automobile",
    ["bmx"] = "bicycle",
    ["kiagt"] = "automobile",
    ["svdisable"] = "automobile",
    ["por718gt4"] = "automobile",
    ["policeb"] = "bike",
    ["fagaloa"] = "automobile",
    ["washington"] = "automobile",
    ["avarus"] = "bike",
    ["youga"] = "automobile",
    ["hpmoto"] = "bike",
    ["panto"] = "automobile",
    ["brutus2"] = "automobile",
    ["inq50eaurouge"] = "automobile",
    ["sanchez2"] = "bike",
    ["chino"] = "automobile",
    ["tribike"] = "bicycle",
    ["hydra"] = "plane",
    ["mercedesamg63"] = "automobile",
    ["tiger1200"] = "bike",
    ["cargobob4"] = "heli",
    ["m5"] = "automobile",
    ["sprinters"] = "automobile",
    ["tribike2"] = "bicycle",
    ["penetrator"] = "automobile",
    ["paradise"] = "automobile",
    ["vacca"] = "automobile",
    ["yosemite"] = "automobile",
    ["pcj"] = "bike",
    ["akuma"] = "bike",
    ["e36rb"] = "automobile",
    ["bagger"] = "bike",
    ["bati2"] = "bike",
    ["phantom2"] = "automobile",
    ["daemon"] = "bike",
    ["pm19"] = "automobile",
    ["cbb"] = "bike",
    ["annihilator"] = "heli",
    ["sls"] = "automobile",
    ["tankercar"] = "train",
    ["double"] = "bike",
    ["vader"] = "bike",
    ["velociraptor"] = "automobile",
    ["trailersmall"] = "trailer",
    ["toros"] = "automobile",
    ["faggio2"] = "bike",
    ["paramedicoambu"] = "automobile",
    ["technical3"] = "automobile",
    ["t20"] = "automobile",
    ["buzzard2"] = "heli",
    ["trailersmall2"] = "trailer",
    ["cargobob"] = "heli",
    ["dynasty"] = "automobile",
    ["cargobob2"] = "heli",
    ["skylift"] = "heli",
    ["polmav"] = "heli",
    ["nemesis"] = "bike",
    ["frogger"] = "heli",
    ["dubsta3"] = "automobile",
    ["dinghy"] = "boat",
    ["m1wb"] = "automobile",
    ["jubilee"] = "automobile",
    ["bestiagts"] = "automobile",
    ["frogger2"] = "heli",
    ["sultan3"] = "automobile",
    ["huntley"] = "automobile",
    ["19raptorsanta"] = "automobile",
    ["duster"] = "plane",
    ["mammatus"] = "plane",
    ["jet"] = "plane",
    ["yosemite3"] = "automobile",
    ["osiris"] = "automobile",
    ["cayman16"] = "automobile",
    ["insurgent2"] = "automobile",
    ["entity3"] = "automobile",
    ["g20stock"] = "automobile",
    ["titan"] = "plane",
    ["lazer"] = "plane",
    ["msls"] = "automobile",
    ["daemon2"] = "bike",
    ["squalo"] = "boat",
    ["emsroamer"] = "automobile",
    ["mers63c"] = "automobile",
    ["marquis"] = "boat",
    ["m4clw"] = "automobile",
    ["dinghy2"] = "boat",
    ["laferrari17"] = "automobile",
    ["lurcher"] = "automobile",
    ["f82"] = "automobile",
    ["jetmax"] = "boat",
    ["tropic"] = "boat",
    ["seashark2"] = "boat",
    ["youga4"] = "automobile",
    ["dukes2"] = "automobile",
    ["freightcar"] = "train",
    ["freightcont2"] = "train",
    ["metrotrain"] = "train",
    ["trailers2"] = "trailer",
    ["21bro"] = "automobile",
    ["trail21pm"] = "automobile",
    ["trailers3"] = "trailer",
    ["raketrailer"] = "trailer",
    ["fcr2"] = "bike",
    ["fcr"] = "bike",
    ["tanker"] = "trailer",
    ["guardian"] = "automobile",
    ["lancerevolution9"] = "automobile",
    ["velum"] = "plane",
    ["italigtb2"] = "automobile",
    ["rmodpagani"] = "automobile",
    ["nissangtr50"] = "automobile",
    ["bifta"] = "automobile",
    ["rebla"] = "automobile",
    ["dune5"] = "automobile",
    ["speeder"] = "boat",
    ["m4disable"] = "automobile",
    ["policiaexplorer"] = "automobile",
    ["chino2"] = "automobile",
    ["paragon2"] = "automobile",
    ["warrener"] = "automobile",
    ["kalahari"] = "automobile",
    ["btype"] = "automobile",
    ["slamvan5"] = "automobile",
    ["rmodgt63"] = "automobile",
    ["audi7"] = "automobile",
    ["hakuchou2"] = "bike",
    ["diablous2"] = "bike",
    ["gt500"] = "automobile",
    ["prototipo"] = "automobile",
    ["vestra"] = "plane",
    ["rhapsody"] = "automobile",
    ["blade"] = "automobile",
    ["pigalle"] = "automobile",
    ["sovereign"] = "bike",
    ["pfister811"] = "automobile",
    ["nimbus"] = "plane",
    ["tenere1200"] = "bike",
    ["besra"] = "plane",
    ["policiasilverado"] = "automobile",
    ["cinquemila"] = "automobile",
    ["trophytruck"] = "automobile",
    ["coquette2"] = "automobile",
    ["hakuchou"] = "bike",
    ["lp770"] = "automobile",
    ["bugattiatlantic"] = "automobile",
    ["rvjeepcherokee"] = "automobile",
    ["faggio"] = "bike",
    ["subaruimpreza"] = "automobile",
    ["furoregt"] = "automobile",
    ["jester2"] = "automobile",
    ["bmwr1250"] = "bike",
    ["massacro2"] = "automobile",
    ["vwgolf"] = "automobile",
    ["i8disable"] = "automobile",
    ["casco"] = "automobile",
    ["youga3"] = "automobile",
    ["conada"] = "heli",
    ["boxville4"] = "automobile",
    ["insurgent"] = "automobile",
    ["technical2"] = "automobile",
    ["halftrack"] = "automobile",
    ["gburrito2"] = "automobile",
    ["hellion"] = "automobile",
    ["dinghy3"] = "boat",
    ["enduro"] = "bike",
    ["s10civil"] = "automobile",
    ["lectro"] = "bike",
    ["champion"] = "automobile",
    ["gsxc110"] = "automobile",
    ["kuruma"] = "automobile",
    ["krieger"] = "automobile",
    ["kuruma2"] = "automobile",
    ["e60"] = "automobile",
    ["trophytruck2"] = "automobile",
    ["amels200"] = "boat",
    ["trash2"] = "automobile",
    ["dominator6"] = "automobile",
    ["limo2"] = "automobile",
    ["avj"] = "automobile",
    ["everon"] = "automobile",
    ["dmons"] = "bike",
    ["rmodbentley1"] = "automobile",
    ["rmodrs6"] = "automobile",
    ["valkyrie"] = "heli",
    ["zr3803"] = "automobile",
    ["swift2"] = "heli",
    ["luxor2"] = "plane",
    ["macan"] = "automobile",
    ["feltzer3"] = "automobile",
    ["policiavictoria"] = "automobile",
    ["boxville5"] = "automobile",
    ["virgo"] = "automobile",
    ["kakuma"] = "bike",
    ["windsor"] = "automobile",
    ["vindicator"] = "bike",
    ["bf400"] = "bike",
    ["brawler"] = "automobile",
    ["stalion"] = "automobile",
    ["maverick2"] = "heli",
    ["tampa2"] = "automobile",
    ["toro"] = "boat",
    ["previon"] = "automobile",
    ["hondafk8"] = "automobile",
    ["faction2"] = "automobile",
    ["moonbeam"] = "automobile",
    ["moonbeam2"] = "automobile",
    ["penumbra2"] = "automobile",
    ["gauntlet4"] = "automobile",
    ["nissangtr3"] = "automobile",
    ["mustangmach1"] = "automobile",
    ["comet3"] = "automobile",
    ["primo2"] = "automobile",
    ["futo2"] = "automobile",
    ["brickade2"] = "automobile",
    ["specter2"] = "automobile",
    ["buccaneer2"] = "automobile",
    ["voodoo"] = "automobile",
    ["trailerlarge"] = "trailer",
    ["btype2"] = "automobile",
    ["cog55"] = "automobile",
    ["nightshade"] = "automobile",
    ["seven70"] = "automobile",
    ["broadway"] = "automobile",
    ["ktmx"] = "automobile",
    ["mamba"] = "automobile",
    ["schafter3"] = "automobile",
    ["windsor2"] = "automobile",
    ["calico"] = "automobile",
    ["schafter5"] = "automobile",
    ["asbo"] = "automobile",
    ["schafter6"] = "automobile",
    ["cog552"] = "automobile",
    ["cognoscenti"] = "automobile",
    ["cognoscenti2"] = "automobile",
    ["gauntlet5"] = "automobile",
    ["esskey"] = "bike",
    ["baller3"] = "automobile",
    ["vectre"] = "automobile",
    ["bombushka"] = "plane",
    ["baller4"] = "automobile",
    ["squaddie"] = "automobile",
    ["ksd"] = "bike",
    ["pro1"] = "automobile",
    ["baller5"] = "automobile",
    ["jester3"] = "automobile",
    ["baller6"] = "automobile",
    ["dinghy4"] = "boat",
    ["ruston"] = "automobile",
    ["370driftmachine"] = "automobile",
    ["tropic2"] = "boat",
    ["supervolito2"] = "heli",
    ["ttrd"] = "automobile",
    ["policiaschaftersid"] = "automobile",
    ["valkyrie2"] = "heli",
    ["banshee2"] = "automobile",
    ["488snl"] = "automobile",
    ["civic"] = "automobile",
    ["coop12"] = "automobile",
    ["faction3"] = "automobile",
    ["minivan2"] = "automobile",
    ["tenere"] = "bike",
    ["tornado5"] = "automobile",
    ["marshall2"] = "automobile",
    ["bentleybacalar"] = "automobile",
    ["imola"] = "automobile",
    ["virgo2"] = "automobile",
    ["xls"] = "automobile",
    ["xls2"] = "automobile",
    ["fmj"] = "automobile",
    ["trai1l5baep"] = "automobile",
    ["rumpo3"] = "automobile",
    ["volatus"] = "heli",
    ["ellie"] = "automobile",
    ["rampage10"] = "automobile",
    ["reaper"] = "automobile",
    ["mercedesg65"] = "automobile",
    ["shelbygt500"] = "automobile",
    ["palio17"] = "automobile",
    ["tug"] = "boat",
    ["diablous"] = "bike",
    ["volsantana"] = "automobile",
    ["vectraa"] = "automobile",
    ["omnis"] = "automobile",
    ["le7b"] = "automobile",
    ["rallytruck"] = "automobile",
    ["cliffhanger"] = "bike",
    ["tropos"] = "automobile",
    ["camv50"] = "automobile",
    ["pcx"] = "bike",
    ["brioso"] = "automobile",
    ["tornado6"] = "automobile",
    ["bruiser2"] = "automobile",
    ["scarab2"] = "automobile",
    ["chimera"] = "quadbike",
    ["raptor"] = "automobile",
    ["vortex"] = "bike",
    ["dick"] = "automobile",
    ["sanctus"] = "bike",
    ["nightblade"] = "bike",
    ["zombiea"] = "bike",
    ["zombieb"] = "bike",
    ["defiler"] = "bike",
    ["ageraone"] = "automobile",
    ["comet6"] = "automobile",
    ["schlagenstr"] = "automobile",
    ["ratbike"] = "bike",
    ["stafford"] = "automobile",
    ["991turbos"] = "automobile",
    ["shotaro"] = "bike",
    ["r300"] = "automobile",
    ["manchez"] = "bike",
    ["hermes"] = "automobile",
    ["db5"] = "automobile",
    ["blazer4"] = "quadbike",
    ["cypher"] = "automobile",
    ["rvx6mf16"] = "automobile",
    ["tempesta"] = "automobile",
    ["dinghy5"] = "boat",
    ["italigtb"] = "automobile",
    ["nero2"] = "automobile",
    ["specter"] = "automobile",
    ["hiluxpc"] = "automobile",
    ["sw4pm"] = "automobile",
    ["dune4"] = "automobile",
    ["monster4"] = "automobile",
    ["wastelander"] = "automobile",
    ["ruiner3"] = "automobile",
    ["turismo2"] = "automobile",
    ["infernus2"] = "automobile",
    ["toyotagodz"] = "automobile",
    ["gp1"] = "automobile",
    ["neo"] = "automobile",
    ["trailers4"] = "trailer",
    ["xa21"] = "automobile",
    ["tenf2"] = "automobile",
    ["weevil2"] = "automobile",
    ["vagner"] = "automobile",
    ["insurgent3"] = "automobile",
    ["scarab3"] = "automobile",
    ["apc"] = "automobile",
    ["rvars3spxxbk"] = "automobile",
    ["blista3"] = "automobile",
    ["rmodmonsterr34"] = "automobile",
    ["dune3"] = "automobile",
    ["ardent"] = "automobile",
    ["seabreeze"] = "plane",
    ["elantra"] = "automobile",
    ["pct18"] = "automobile",
    ["rcf"] = "automobile",
    ["levante"] = "automobile",
    ["tula"] = "plane",
    ["havok"] = "heli",
    ["hunter"] = "heli",
    ["microlight"] = "plane",
    ["openwheel1"] = "automobile",
    ["romeo155"] = "automobile",
    ["rogue"] = "plane",
    ["gb200"] = "automobile",
    ["rmodp1gtr"] = "automobile",
    ["pyro"] = "plane",
    ["vetir"] = "automobile",
    ["howard"] = "plane",
    ["stalion2"] = "automobile",
    ["mogul"] = "plane",
    ["starling"] = "plane",
    ["nokota"] = "plane",
    ["molotok"] = "plane",
    ["retinue"] = "automobile",
    ["cyclone"] = "automobile",
    ["gsxr19"] = "bike",
    ["viseris"] = "automobile",
    ["comet5"] = "automobile",
    ["riata"] = "automobile",
    ["autarch"] = "automobile",
    ["savestra"] = "automobile",
    ["comet4"] = "automobile",
    ["neon"] = "automobile",
    ["sentinel3"] = "automobile",
    ["x3sianr21"] = "automobile",
    ["khanjali"] = "automobile",
    ["volatol"] = "plane",
    ["akula"] = "heli",
    ["audirs7"] = "automobile",
    ["deluxo"] = "automobile",
    ["stromberg"] = "automobile",
    ["riot2"] = "automobile",
    ["avenger"] = "plane",
    ["avenger2"] = "plane",
    ["f800"] = "bike",
    ["formula2"] = "automobile",
    ["thruster"] = "heli",
    ["deathbike3"] = "bike",
    ["streiter"] = "automobile",
    ["pariah"] = "automobile",
    ["kamacho"] = "automobile",
    ["rubilord"] = "automobile",
    ["entity2"] = "automobile",
    ["remus"] = "automobile",
    ["cheburek"] = "automobile",
    ["caracara"] = "automobile",
    ["astron"] = "automobile",
    ["c10custom"] = "automobile",
    ["c63w205"] = "automobile",
    ["impaler3"] = "automobile",
    ["zr380"] = "automobile",
    ["hotring"] = "automobile",
    ["fordgtmkiv"] = "automobile",
    ["seasparrow"] = "heli",
    ["michelli"] = "automobile",
    ["dominator3"] = "automobile",
    ["tezeract"] = "automobile",
    ["mp412c"] = "automobile",
    ["issi3"] = "automobile",
    ["scramjet"] = "automobile",
    ["deity"] = "automobile",
    ["nlargo"] = "automobile",
    ["strikeforce"] = "plane",
    ["joyster"] = "automobile",
    ["terbyte"] = "automobile",
    ["cadesclimosine"] = "automobile",
    ["pbus2"] = "automobile",
    ["oppressor2"] = "bike",
    ["merbenw111"] = "automobile",
    ["speedo4"] = "automobile",
    ["freecrawler"] = "automobile",
    ["sc18hartge"] = "automobile",
    ["rmodx6police"] = "automobile",
    ["mule4"] = "automobile",
    ["vwstance"] = "automobile",
    ["menacer"] = "automobile",
    ["trail14civil"] = "automobile",
    ["blimp3"] = "trailer",
    ["jesko"] = "automobile",
    ["720sp"] = "automobile",
    ["swinger"] = "automobile",
    ["rmodbmwm8"] = "automobile",
    ["patriot2"] = "automobile",
    ["italigto"] = "automobile",
    ["monster5"] = "automobile",
    ["22m5santa"] = "automobile",
    ["deathbike2"] = "bike",
    ["impaler4"] = "automobile",
    ["slamvan4"] = "automobile",
    ["718b"] = "automobile",
    ["mazdadead"] = "automobile",
    ["dodgepolara"] = "automobile",
    ["brutus"] = "automobile",
    ["deathbike"] = "bike",
    ["dominator4"] = "automobile",
    ["lanchapk"] = "boat",
    ["dominator5"] = "automobile",
    ["seminole2"] = "automobile",
    ["mule5"] = "automobile",
    ["2018cruzrs"] = "automobile",
    ["bruiser"] = "automobile",
    ["rcbandito"] = "automobile",
    ["blista2"] = "automobile",
    ["cerberus"] = "automobile",
    ["sw4baep"] = "automobile",
    ["monster3"] = "automobile",
    ["tulip"] = "automobile",
    ["bmwe70"] = "automobile",
    ["lamborghinihuracanlw"] = "automobile",
    ["zhaba"] = "automobile",
    ["scarab"] = "automobile",
    ["vamos"] = "automobile",
    ["imperator"] = "automobile",
    ["imperator2"] = "automobile",
    ["cb650r"] = "bike",
    ["imperator3"] = "automobile",
    ["deviant"] = "automobile",
    ["impaler"] = "automobile",
    ["zr3802"] = "automobile",
    ["toyotasupra2"] = "automobile",
    ["paragon"] = "automobile",
    ["jugular"] = "automobile",
    ["boss429"] = "automobile",
    ["rrocket"] = "quadbike",
    ["peyote2"] = "automobile",
    ["s80"] = "automobile",
    ["zorrusso"] = "automobile",
    ["glendale2"] = "automobile",
    ["rmodsupra"] = "automobile",
    ["issi7"] = "automobile",
    ["paramedicoheli"] = "heli",
    ["locust"] = "automobile",
    ["emerus"] = "automobile",
    ["m6gc"] = "automobile",
    ["gauntlet3"] = "automobile",
    ["nebula"] = "automobile",
    ["zion3"] = "automobile",
    ["volatusblack"] = "heli",
    ["drafter"] = "automobile",
    ["911t4s2"] = "automobile",
    ["cls63s"] = "automobile",
    ["minitank"] = "automobile",
    ["blazerpm"] = "automobile",
    ["yosemite2"] = "automobile",
    ["stryder"] = "quadbike",
    ["jb7002"] = "automobile",
    ["sultan2"] = "automobile",
    ["sugoi"] = "automobile",
    ["formula"] = "automobile",
    ["furia"] = "automobile",
    ["vstr"] = "automobile",
    ["kanjo"] = "automobile",
    ["imorgon"] = "automobile",
    ["coquette4"] = "automobile",
    ["landstalker2"] = "automobile",
    ["aventadorgodz"] = "automobile",
    ["ultimagt"] = "automobile",
    ["club"] = "automobile",
    ["dukes3"] = "automobile",
    ["openwheel2"] = "automobile",
    ["peyote3"] = "automobile",
    ["st"] = "automobile",
    ["veto2"] = "automobile",
    ["italirsx"] = "automobile",
    ["z1000"] = "bike",
    ["rs4"] = "automobile",
    ["s8w12"] = "automobile",
    ["toreador"] = "automobile",
    ["slamtruck"] = "automobile",
    ["weevil"] = "automobile",
    ["alkonost"] = "plane",
    ["seasparrow2"] = "heli",
    ["kosatka"] = "trailer",
    ["freightcar2"] = "train",
    ["dominator7"] = "automobile",
    ["dominator8"] = "automobile",
    ["euros"] = "automobile",
    ["tailgater2"] = "automobile",
    ["growler"] = "automobile",
    ["zr350"] = "automobile",
    ["warrener2"] = "automobile",
    ["reever"] = "bike",
    ["iwagen"] = "automobile",
    ["chevette"] = "automobile",
    ["baller7"] = "automobile",
    ["sentinel4"] = "automobile",
    ["buffalo4"] = "automobile",
    ["cb500x"] = "bike",
    ["ignus"] = "automobile",
    ["stelvioqv"] = "automobile",
    ["granger2"] = "automobile",
    ["ruiner4"] = "automobile",
    ["brioso3"] = "automobile",
    ["g65"] = "automobile",
    ["wrangler86"] = "automobile",
    ["kanjosj"] = "automobile",
    ["f82st"] = "automobile",
    ["dalla1"] = "automobile",
    ["postlude"] = "automobile",
    ["torero2"] = "automobile",
    ["rmodc63amg"] = "automobile",
    ["lm87"] = "automobile",
    ["tenf"] = "automobile",
    ["rhinehart"] = "automobile",
    ["greenwood"] = "automobile",
    ["sm722"] = "automobile",
    ["17silvbb"] = "automobile",
    ["rmodcamaro"] = "automobile",
    ["tahoma"] = "automobile",
    ["issi8"] = "automobile",
    ["polas350"] = "heli",
    ["merchospital"] = "automobile",
    ["virtue"] = "automobile",
    ["eudora"] = "automobile",
    ["r8lb"] = "automobile",
    ["powersurge"] = "bike",
    ["journey2"] = "automobile",
    ["dodgeram2500"] = "automobile",
    ["manchez3"] = "bike",
    ["surfer3"] = "automobile",
    ["yurirrmansory"] = "automobile",
    ["cargoplane2"] = "plane",
    ["submersible2"] = "trailer",
    ["rvs10hc"] = "automobile",
    ["dukes"] = "automobile",
    ["eclipse"] = "automobile",
    ["onipc1"] = "automobile",
    ["dominator2"] = "automobile",
    ["dodo"] = "plane",
    ["marshall"] = "automobile",
    ["pegeout206"] = "automobile",
    ["trx22"] = "automobile",
    ["gauntlet2"] = "automobile",
    ["ambulancia"] = "automobile",
    ["a45amg"] = "automobile",
    ["as350samu"] = "heli",
    ["fcb500meck"] = "bike",
    ["rvbnr34"] = "automobile",
    ["2017raptor"] = "automobile",
    ["fusionnas"] = "automobile",
    ["poltowtruck"] = "automobile",
    ["fflatbed3meck"] = "automobile",
    ["fhelimeck"] = "heli",
    ["g20wide"] = "automobile",
    ["panamerasanta"] = "automobile",
    ["g63amg6x6"] = "automobile",
    ["rvmercedesg65"] = "automobile",
    ["r8c20"] = "automobile",
    ["m4c"] = "automobile",
    ["toy86"] = "automobile",
    ["m5e60wb"] = "automobile",
    ["ram22trx"] = "automobile",
    ["488"] = "automobile",
    ["zx10r"] = "bike",
    ["12mp4m"] = "automobile",
    ["trail17baep"] = "automobile",
    ["c63spd"] = "automobile",
    ["r8v10"] = "automobile",
    ["c63scpd"] = "automobile",
    ["s63m"] = "automobile",
    ["gmt900escalade"] = "automobile",
    ["cayenne"] = "automobile",
    ["taycan21pr"] = "automobile",
    ["lw458s"] = "automobile",
    ["ram226x6"] = "automobile",
    ["panameramansory"] = "automobile",
    ["gt2rsmr"] = "automobile",
    ["acs8"] = "automobile",
    ["babyamarok"] = "automobile",
    ["mraptor"] = "automobile",
    ["m600"] = "automobile",
    ["cayennerod"] = "automobile",
    ["gcmgolf8r"] = "automobile",
    ["hrv22"] = "automobile",
    ["huragucci"] = "automobile",
    ["supra2"] = "automobile",
    ["hycadem8"] = "automobile",
    ["ivecodualcab"] = "automobile",
    ["luxury1"] = "boat",
    ["fox"] = "automobile",
    ["mansgt"] = "automobile",
    ["scaniar700box"] = "automobile",
    ["volatusyuri"] = "heli",
    ["robertofirmino"] = "automobile",
    ["crown210"] = "automobile",
    ["cbr"] = "bike",
    ["wazuma"] = "quadbike",
    ["pgt3rs19"] = "automobile",
    ["bmwboltz"] = "automobile",
    ["gls63"] = "automobile",
    ["italia458"] = "automobile",
    ["mcst"] = "automobile",
    ["tesroad20"] = "automobile",
    ["x6mf16"] = "automobile",
    ["er34n"] = "automobile",
    ["19raptor"] = "automobile",
    ["srt8b"] = "automobile",
    ["auditt"] = "automobile",
    ["bmci"] = "automobile",
    ["bdivo"] = "automobile",
    ["bmistralw16"] = "automobile",
    ["cayenneturbo"] = "automobile",
    ["fd"] = "automobile",
    ["g656x6"] = "automobile",
    ["ap2"] = "automobile",
    ["srt8"] = "automobile",
    ["gtr"] = "automobile",
    ["stradale18"] = "automobile",
    ["lamboreventon"] = "automobile",
    ["regera16"] = "automobile",
    ["kcorolla"] = "automobile",
    ["famarok"] = "automobile",
    ["ksonata"] = "automobile",
    ["rvmecahp"] = "automobile",
    ["ktouring"] = "automobile",
    ["cox2013"] = "automobile",
    ["lykan"] = "automobile",
    ["f150"] = "automobile",
    ["raptor2017"] = "automobile",
    ["bmwm5f90"] = "automobile",
    ["gtrlb"] = "automobile",
    ["aventador"] = "automobile",
    ["laferrari"] = "automobile",
    ["m5f90"] = "automobile",
    ["h2carb"] = "bike",
    ["mondeo"] = "automobile",
    ["outlaw2"] = "automobile",
    ["skorpion"] = "automobile",
    ["teslamodels"] = "automobile",
    ["tulenis"] = "automobile",
    ["sonata20"] = "automobile",
    ["benze55"] = "automobile",
    ["m3e36"] = "automobile",
    ["f824slw"] = "automobile",
    ["f82lw"] = "automobile",
    ["rvmercedesgt63"] = "automobile",
    ["rmodfordpolice"] = "automobile",
    ["f82hs"] = "automobile",
    ["911rwb"] = "automobile",
    ["tofu"] = "automobile",
    ["jeepg"] = "automobile",
    ["mansamgt21"] = "automobile",
    ["models"] = "automobile",
    ["chevimpalals06"] = "automobile",
    ["s4avant"] = "automobile",
    ["rmodlego1"] = "automobile",
    ["babylancer"] = "automobile",
    ["rvbm422pxx2ncs"] = "automobile",
    ["dusterpmesp"] = "automobile",
    ["ody18"] = "automobile",
    ["impreza"] = "automobile",
    ["e63s"] = "automobile",
    ["srt8bhp"] = "automobile",
    ["rsvr16"] = "automobile",
    ["trail22baep"] = "automobile",
    ["saveirog7"] = "automobile",
    ["toyotasj"] = "automobile",
    ["dodgechargersrt"] = "automobile",
    ["aaq4"] = "automobile",
    ["c42"] = "automobile",
    ["pacehp"] = "automobile",
    ["lsen"] = "automobile",
    ["blackferrari812"] = "automobile",
    ["trail19rt"] = "automobile",
    ["hiluxeb"] = "automobile",
    ["mustangfast"] = "automobile",
    ["sato"] = "automobile",
    ["sennasmso1"] = "automobile",
    ["wraith"] = "automobile",
    ["xre300"] = "bike",
    ["675ltsp"] = "automobile",
    ["tiger2021"] = "bike",
    ["160"] = "bike",
    ["transalp"] = "bike",
    ["frauscher16"] = "boat",
    ["a45disable"] = "automobile",
    ["agerars"] = "automobile",
    ["gt86b"] = "automobile",
    ["fordmustrtrx"] = "automobile",
    ["porsche930"] = "automobile",
    ["m4cvo"] = "automobile",
    ["grantorsport"] = "automobile",
    ["f250gtberlus"] = "automobile",
    ["blazerft"] = "automobile",
    ["chevcar1975"] = "automobile",
    ["2000gt"] = "automobile",
    ["devilz"] = "automobile",
    ["s800cabrio"] = "automobile",
    ["ps30"] = "automobile",
    ["blazer41"] = "automobile",
    ["huracan"] = "automobile",
    ["blazer31"] = "automobile",
    ["blazer21"] = "automobile",
    ["bmwm7602017"] = "automobile",
    ["blazer1"] = "automobile",
    ["xls1"] = "automobile",
    ["lex570"] = "automobile",
    ["rocoto12"] = "automobile",
    ["sultan1"] = "automobile",
    ["landstalker1"] = "automobile",
    ["tailgater12"] = "automobile",
    ["m2"] = "automobile",
    ["chevopalss475"] = "automobile",
    ["policiabmwr1200"] = "bike",
    ["coopers"] = "automobile",
    ["pmspin"] = "automobile",
    ["250c"] = "automobile",
    ["fk2"] = "automobile",
    ["tts"] = "automobile",
    ["bbentayga"] = "automobile",
    ["huayra14"] = "automobile",
    ["enzo02"] = "automobile",
    ["911turbos"] = "automobile",
    ["amggtr"] = "automobile",
    ["policiacapricesid"] = "automobile",
    ["x5m13"] = "automobile",
    ["huracangt3evo"] = "automobile",
    ["murlagolb"] = "automobile",
    ["polvauxhastra"] = "automobile",
    ["knightrider"] = "automobile",
    ["sarenigt3"] = "automobile",
    ["mgtc49a"] = "automobile",
    ["m8competition"] = "automobile",
    ["lotusesprit"] = "automobile",
    ["fordf1501949"] = "automobile",
    ["monaro"] = "automobile",
    ["cv8"] = "automobile",
    ["gtr17"] = "automobile",
    ["rufrt12"] = "automobile",
    ["911gt3rs"] = "automobile",
    ["720s"] = "automobile",
    ["fj402"] = "automobile",
    ["bmwx5m2017"] = "automobile",
    ["chevelless"] = "automobile",
    ["w201"] = "automobile",
    ["isuzu19"] = "automobile",
    ["964cabrio"] = "automobile",
    ["lp570ap"] = "automobile",
    ["w204amgc"] = "automobile",
    ["w210amg"] = "automobile",
    ["rs6"] = "automobile",
    ["sq5"] = "automobile",
    ["contgt2011"] = "automobile",
    ["dart68"] = "automobile",
    ["chino1"] = "automobile",
    ["por930"] = "automobile",
    ["lx570"] = "automobile",
    ["pajieluo"] = "automobile",
    ["audia630t2008"] = "automobile",
    ["s1"] = "automobile",
    ["bmwhommage"] = "automobile",
    ["chevrcelta"] = "automobile",
    ["chevrimpala85"] = "automobile",
    ["1500dj"] = "automobile",
    ["mercedesa45"] = "automobile",
    ["citroenxantia"] = "automobile",
    ["mazda6mps2006"] = "automobile",
    ["e63amg"] = "automobile",
    ["fc3bn"] = "automobile",
    ["porcarrs95"] = "automobile",
    ["may62s"] = "automobile",
    ["8pralift"] = "automobile",
    ["tesmods"] = "automobile",
    ["s5"] = "automobile",
    ["e46rb"] = "automobile",
    ["cherokee1"] = "automobile",
    ["toylancrugx"] = "automobile",
    ["lwas5"] = "automobile",
    ["nisonebre"] = "automobile",
    ["zeus"] = "automobile",
    ["a6hl"] = "automobile",
    ["cresta"] = "automobile",
    ["subn"] = "automobile",
    ["slk55"] = "automobile",
    ["cats"] = "automobile",
    ["m6f13"] = "automobile",
    ["hornet"] = "bike",
    ["fordgt17"] = "automobile",
    ["rvrt70"] = "automobile",
    ["silv86"] = "automobile",
    ["mb6"] = "automobile",
    ["ktklp7704"] = "automobile",
    ["cliors"] = "automobile",
    ["cobra"] = "automobile",
    ["gaz24cabrio"] = "automobile",
    ["fiattoro17"] = "automobile",
    ["pontiacg8"] = "automobile",
    ["patrold"] = "automobile",
    ["yfef12a"] = "automobile",
    ["paliopm1"] = "automobile",
    ["bmw335isedan"] = "automobile",
    ["giulia"] = "automobile",
    ["p1"] = "automobile",
    ["lexis350fsport"] = "automobile",
    ["priustaxi"] = "automobile",
    ["rs4avant"] = "automobile",
    ["alpinae30"] = "automobile",
    ["alfrommito"] = "automobile",
    ["ahksv"] = "automobile",
    ["4881"] = "automobile",
    ["fulux63"] = "automobile",
    ["xjr"] = "automobile",
    ["merbenv250blu"] = "automobile",
    ["tricolore"] = "automobile",
    ["hellcat"] = "automobile",
    ["vaz2110lad110"] = "automobile",
    ["p911h"] = "automobile",
    ["gle53"] = "automobile",
    ["dustercivil"] = "automobile",
    ["babycherokee"] = "automobile",
    ["babyr34"] = "automobile",
    ["babygtr35c"] = "automobile",
    ["franco125"] = "boat",
    ["sr650fly"] = "boat",
    ["yacht3a"] = "boat",
    ["rmodm4"] = "automobile",
    ["bmws"] = "bike",
    ["bnr342"] = "automobile",
    ["bolide"] = "automobile",
    ["chironss"] = "automobile",
    ["19gt500"] = "automobile",
    ["930mnc"] = "automobile",
    ["2015a3"] = "automobile",
    ["silverado17"] = "automobile",
    ["titan60"] = "bike",
    ["s3sedan"] = "automobile",
    ["armj"] = "automobile",
    ["cam8tun"] = "automobile",
    ["cb90h"] = "quadbike",
    ["aven15lw"] = "automobile",
    ["barcspeeder"] = "bike",
    ["bc"] = "automobile",
    ["bowserjr"] = "trailer",
    ["gmcs"] = "automobile",
    ["rangerover"] = "automobile",
    ["m3disable"] = "automobile",
    ["nis15"] = "automobile",
    ["rmodm3e36"] = "automobile",
    ["evo9"] = "automobile",
    ["f12ber"] = "automobile",
    ["h2carbpol"] = "bike",
    ["nc1"] = "automobile",
    ["amgdisable"] = "automobile",
    ["lancerevolutionx"] = "automobile",
    ["m3f80"] = "automobile",
    ["m4clb"] = "automobile",
    ["rmodgt63mini"] = "automobile",
    ["m1disable"] = "automobile",
    ["velar"] = "automobile",
    ["trail21dft"] = "automobile",
    ["valkyrietp"] = "automobile",
    ["panameradisable"] = "automobile",
    ["911disable"] = "automobile",
    ["r8disable"] = "automobile",
    ["taigun21"] = "automobile",
    ["supradisable"] = "automobile",
    ["huracanllwdisable"] = "automobile",
    ["punto"] = "automobile",
    ["qashqai16"] = "automobile",
    ["rmod69police"] = "automobile",
    ["rmode63s"] = "automobile",
    ["rs6disable"] = "automobile",
    ["rmodjeep"] = "automobile",
    ["rmodmartin"] = "automobile",
    ["rmodgt63police"] = "automobile",
    ["rmodsianr"] = "automobile",
    ["rmodzl1"] = "automobile",
    ["rmodzl1police"] = "automobile",
    ["rmodf12tdf"] = "automobile",
    ["rmodjesko"] = "automobile",
    ["rmodbentleygt"] = "automobile",
    ["rmodchiron300"] = "automobile",
    ["rmodm8gte"] = "automobile",
    ["rmodskyline34"] = "automobile",
    ["rmodlego2"] = "automobile",
    ["policiacharger2018"] = "automobile",
    ["policiamustanggt"] = "automobile",
    ["policiaheli"] = "heli",
    ["paramedicocharger2014"] = "automobile",
    ["s10hc"] = "automobile",
    ["italiadisable"] = "automobile",
    ["fordmustang"] = "automobile",
    ["nissangtr"] = "automobile",
    ["teslaprior"] = "automobile",
    ["huracandisable"] = "automobile",
    ["dodgedesativado"] = "automobile",
    ["nismodesativado"] = "automobile",
    ["lancerdisable"] = "automobile",
    ["nissan370z"] = "automobile",
    ["biz"] = "bike",
    ["elva"] = "automobile",
    ["excavator"] = "automobile",
    ["fiorino"] = "automobile",
    ["gemera"] = "automobile",
    ["biz25"] = "bike",
    ["foxsnt"] = "automobile",
    ["alfmito"] = "automobile",
    ["monza"] = "automobile",
    ["rmodbolide"] = "automobile",
    ["rmodlegoporsche"] = "automobile",
    ["rmodmonster"] = "automobile",
    ["rmodmonstergt"] = "automobile",
    ["rmodsuprapandem"] = "automobile",
    ["rmodtracktor"] = "automobile",
    ["rmodtracktor2"] = "automobile",
    ["taycan"] = "automobile",
    ["rmodessenza"] = "automobile",
    ["ars3spxxbk"] = "automobile",
    ["rs6avant20"] = "automobile",
    ["urus"] = "automobile",
    ["vwfusca"] = "automobile",
    ["trail22civilcmd"] = "automobile",
    ["2500ram"] = "automobile",
    ["dodge2500"] = "automobile",
    ["focusst"] = "automobile",
    ["mk7golf"] = "automobile",
    ["raptorsom"] = "automobile",
    ["s10som"] = "automobile",
    ["urussanta"] = "automobile",
    ["bmxbaby"] = "bike",
    ["r1250"] = "bike",
    ["eclipsepol"] = "automobile",
    ["rvgxrx7"] = "automobile",
    ["rvnis15"] = "automobile",
    ["silvias15"] = "automobile",
    ["nissangtrnismo"] = "automobile",
    ["skyliner34"] = "automobile",
    ["lamborghinihuracan"] = "automobile",
    ["bmwm4gts"] = "automobile",
    ["bmwm5e34"] = "automobile",
    ["civictyper"] = "automobile",
    ["toyotasupra"] = "automobile",
    ["mercedesgt63"] = "automobile",
    ["blackferrarif12"] = "automobile",
    ["blackferrariitalia"] = "automobile",
    ["bmwi8"] = "automobile",
    ["mclarensenna"] = "automobile",
    ["acuransx"] = "automobile",
    ["golfgti"] = "automobile",
    ["golfmk7"] = "automobile",
    ["subarubrz"] = "automobile",
    ["350z"] = "automobile",
    ["escaladegt900"] = "automobile",
    ["escalade2021"] = "automobile",
    ["dodgecharger1970"] = "automobile",
    ["xtrocam"] = "bike",
    ["bmwm1wb"] = "automobile",
    ["wheelchair"] = "automobile",
    ["blackferrarif40"] = "automobile",
    ["dodgechargerrt69"] = "automobile",
    ["r1"] = "bike",
    ["r6"] = "bike",
    ["camaro"] = "automobile",
    ["mustang1969"] = "automobile",
    ["corvettec7"] = "automobile",
    ["audirs6"] = "automobile",
    ["audir8"] = "automobile",
    ["porsche911"] = "automobile",
    ["amarokpol"] = "automobile",
    ["hger"] = "heli",
    ["blazerbaep"] = "automobile",
    ["trail21baep"] = "automobile",
    ["trail21dbaep"] = "automobile",
    ["trail22baepcmd"] = "automobile",
    ["paliocivil"] = "automobile",
    ["spincivil"] = "automobile",
    ["trail22crgcmd"] = "automobile",
    ["trail15pm"] = "automobile",
    ["dusterexercito"] = "automobile",
    ["golexercito"] = "automobile",
    ["palioexercito"] = "automobile",
    ["spinexercito"] = "automobile",
    ["trail22ebcmd"] = "automobile",
    ["trail15ft"] = "automobile",
    ["trail21ft"] = "automobile",
    ["trail22ft1"] = "automobile",
    ["trail22ftcmd"] = "automobile",
    ["golpm"] = "automobile",
    ["spinpm"] = "automobile",
    ["trail17pm"] = "automobile",
    ["trail22pm"] = "automobile",
    ["blazerrota"] = "automobile",
    ["sw4rota"] = "automobile",
    ["trail15rota"] = "automobile",
    ["trail17rota"] = "automobile",
    ["trail21drota"] = "automobile",
    ["as350"] = "heli",
    ["flatbed3"] = "automobile",
    ["xre2019pm1"] = "bike",
}

CreateThread(function()
    if CityConfig[cityName] then
        CityConfig[cityName]()
    end
end)

exports("GetGarages",function()
    return Garages
end)

exports("GetGarageVips",function()
    return GarageVips
end)

exports("GetGarageWorks",function()
    return GarageWorks
end)

exports("GetVehicleType",function(Name)
	return VehicleTypes[Name]
end)
