Suggestions = {
	{ name = _t("cmd.id.name"), help = _t("cmd.id")  },
	{ name = _t("cmd.carry.name"), help = _t("cmd.carry")  },
	{ name = _t("cmd.frisk.name"), help = _t("cmd.frisk")  },
	{ name = _t("cmd.farm.name"), help = _t("cmd.farm")  },
	{ name = _t("cmd.panel.name"), help = _t("cmd.panel")  },
	{ name = _t("cmd.world.event.name"), help = _t("cmd.world.event")  },
	{ name = _t("cmd.world.default.name"), help = _t("cmd.world.default")  },
	{ name = _t("cmd.fps.name"), help = _t("cmd.fps")  },
	{ name = _t("cmd.clothes.name"), help = _t("cmd.clothes")  },
	{ name = _t("cmd.fac.name"), help = _t("cmd.fac")  },
	{ name = _t("cmd.help.name"), help = _t("cmd.help")  },
	{ name = _t("cmd.walk.name"), help = _t("cmd.walk")  },
	{ name = _t("cmd.dance.name"), help = _t("cmd.dance")  },
	{ name = _t("cmd.tiktok.name"), help = _t("cmd.tiktok")  },
}

Block = {
	"zap",
	"lixo",
	"macaco",
	"preto",
	"arrombado",
	"viadinho",
	"urugutango",
	"gorila",
	"gorilla",
	"mongoloide",
	"bixa",
	"bicha",
	"traveco",
	"veveco",
	"boiola",
	"pau",
	"buceta",
	"gay",
	"piranha",
	"monkey",
	"vagabunda",
	"puta",
	"escroto",
	"piranha",
	"pretinho",
	"escurinho",
	"negrinho",
	"piranha"
}
