cityName = GetConvar("cityName", "")

farmGroupConfig = {
    -- ["Ballas"] = {"Armas","Municao"},
}

farmConfig = {
    ["Armas"] = {
        "weaponbody",
        "molas"
    },
    ["Municao"] = {
        "polvora",
        "capsula"
    },
    ["Maconha"] = {
        "silk",
        "weedleaf"
    },
    ["Metafetamina"] = {
        "saline",
        "acetone"
    },
    ["Cocaina"] = {
        "cokeleaf",
        "sulfuric"
    },
    ["Lavagem"] = {
        "aguadestilada",
        "cloro"
    },
    ["Desmanche"] = {
        "dinheirosujo"
    },

}

if cityName == "Santa" then
    farmGroupConfig = {

        ["Vermelhos"] = {"Cocaina"},
        ["Verdes"] = {"Cocaina"},
        ["Rosas"] = {"Cocaina"},
        ["LosAztecas"] = {"Cocaina"},
        ["Amarelos"] = {"Cocaina"},

        ["Vagos"] = {"Metafetamina"},
        ["Umbrella"] = {"Metafetamina"},
        ["AlcateiaHsT"] = {"Metafetamina"},
        ["Afetados"] = {"Metafetamina"},
        ["Pinkmans"] = {"Metafetamina"},
        ["Hollywood"] = {"Metafetamina"},
        ["Brancos"] = {"Metafetamina"},

        ["Barragem"] =  {"Maconha"},
        ["Gang9"] = {"Maconha"},
        ["Banzas"] = {"Maconha"},
        ["Dixavas"] = {"Maconha"},
        ["Sindicato"] = {"Maconha"},
        ["Laranjas"] = {"Maconha"},

        ["Gang2"] = {"Municao"},
        ["Tribo"] = {"Municao"},
        ["Campinho"] = {"Municao"},
        ["Gang4"] = {"Municao"},
        ["Inglaterra"] = {"Municao"},
        ["Fazendinha"] = {"Armas"},
        ["Outlaws"] = {"Municao"},
        ["SonsofAnarchy"] = {"Municao"},
        ["Gang3"] = {"Municao"},
        ["Gang8"] = {"Municao"},
        ["Gang7"] = {"Municao"},
        ["Gang5"] = {"Municao"},
        ["Marrons"] = {"Municao"},
        ["Cinzas"] = {"Municao"},
        ["Azuis"] = {"Municao"},
        ["Warlocks"] = {"Municao"},
        ["Groove"] = {"Municao"}, 
        ["Galaxy"] = {"Municao"},    
        ["Callisto"] = {"Municao"},
        ["Roxos"] = {"Municao"},
        ["Bahamas"] = {"Municao"},
        ["LosTugas"] = {"Municao"},
        

        ["Gang1"] = {"Armas"},
        ["Tropadu7"] = {"Armas"},
        ["Japao"] = {"Armas"},
        ["Mercenarios"] = {"Armas"},
        ["Caribe"] = {"Armas"},
        ["Noxus"] = {"Armas"},
        ["LaMafia"] = {"Armas"},
        ["Gang6"] = {"Armas"},
        ["Metgala"] = {"Armas"},
        ["Gringa"] = {"Armas"},
        ["Franca"] = {"Armas"},
        ["Italia"] = {"Armas"},
        ["Russia"] = {"Armas"},
        ["Israel"] = {"Armas"},
        ["Playboy"] = {"Armas"},
        ["Mexico"] = {"Armas"},
        ["China"] = {"Armas"},

        ["Ballas"] =  {"Lavagem"},
        ["Bellagio"] = {"Lavagem"},
        ["Lavajato"] = {"Lavagem"},
        ["Tequilas"] = {"Lavagem"},
        ["Arcade"] = {"Lavagem"},
        ["Palazzo"] = {"Lavagem"},
        ["Luxor"] = {"Lavagem"},
        ["Putaria"] =  {"Lavagem"},

        ["Overdrive"] = {"Desmanche"},
        ["Bennys"] = {"Desmanche"},
        ["DriftKing"] = {"Desmanche"},
        ["Virtude"] = {"Desmanche"},
        ["TopGear"] = {"Desmanche"},
        ["Forza"] = {"Desmanche"},
        ["CarClube"] = {"Desmanche"},
        ["Kraken"] = {"Desmanche"},
        ["Outlaws"] = {"Desmanche"},
        ["Big"] = {"Desmanche"},
        ["Redline"] = {"Desmanche"},

    }
elseif cityName == "CidadeNobre" then
    farmGroupConfig = {        
        ["Banzas"] = {"Maconha"},        
        ["Sindicato"] = {"Maconha"},
        ["Laranjas"] = {"Maconha"},
        ["Gang8"] = {"Maconha"},
        ["Gang7"] = {"Maconha"},
        ["LosAztecas"] = {"Maconha"},
        ["Barragem"] =  {"Maconha"},

        ["Vagos"] =  {"Metafetamina"},
        ["Gang6"] = {"Metafetamina"},
        ["LaMafia"] = {"Metafetamina"},        
        ["Umbrella"] = {"Metafetamina"},
        ["Afetados"] = {"Metafetamina"},
        ["Hollywood"] = {"Metafetamina"},
        ["Amarelos"] = {"Metafetamina"},
        ["AlcateiaHsT"] = {"Metafetamina"},
        ["Callisto"] = {"Metafetamina"},
        ["Azuis"] = {"Metafetamina"},
        ["Vermelhos"] =  {"Metafetamina"},

        ["Gang9"] = {"Cocaina"},
        ["Brancos"] = {"Cocaina"},
        ["Rosas"] = {"Cocaina"},        
        ["Roxos"] = {"Cocaina"},
        ["DriftKing"] = {"Cocaina"},  
        
        ["Pinkmans"] = {"Lavagem"},
        ["Ballas"] =  {"Lavagem"},
        ["Metgala"] = {"Lavagem"},     
        ["Tequilas"] = {"Lavagem"},
        ["Arcade"] = {"Lavagem"},        
        ["Bahamas"] = {"Lavagem"},        
        ["Luxor"] = {"Lavagem"},
        ["Redline"] = {"Lavagem"},
        ["Gang1"] =  {"Lavagem"},
        ["FerroVelho"] = {"Lavagem"},

        ["Gang2"] =  {"Municao"},
        ["Caribe"] =  {"Municao"},
        ["Kraken"] =  {"Municao"},
        ["Cinzas"] = {"Municao"},
        ["Bellagio"] =  {"Municao"},
        ["Tropadu7"] =  {"Municao"},
        ["Tribo"] = {"Municao"},
        ["Gang4"] = {"Municao"},
        ["Outlaws"] = {"Municao"},
        ["SonsofAnarchy"] = {"Municao"},
        ["Anonymous"] = {"Municao"},
        ["Fazendinha"] = {"Municao"},
        ["Campinho"] = {"Municao"},
        ["Gang3"] = {"Municao"},
        ["Morro-do-Sacola"] = {"Municao"},        
        ["Gang5"] = {"Municao"},
        ["Marrons"] = {"Municao"},        
        ["Warlocks"] = {"Municao"},
        ["Inglaterra"] = {"Municao"},
        ["Galaxy"] = {"Municao"},
        ["Verdes"] = {"Municao"},
        
        ["Dixavas"] = {"Armas"},
        ["Putaria"] = {"Armas"},
        ["Palazzo"] = {"Armas"},
        ["Mercenarios"] =  {"Armas"},        
        ["Franca"] = {"Armas"},
        ["Japao"] =  {"Armas"},
        ["Lavajato"] = {"Armas"},        
        -- ["Inglaterra"] =  {"Armas"},
        
        ["Gringa"] =  {"Armas"},
        ["Italia"] = {"Armas"},
        ["Russia"] = {"Armas"},
        ["Israel"] = {"Armas"},
        ["Playboy"] = {"Armas"},
        ["Mexico"] = {"Armas"},
        ["China"] = {"Armas"},
        ["Noxus"] = {"Armas"},
        
        ["TopGear"] = {"Desmanche"},
        ["Groove"] = {"Desmanche"},
        ["Bennys"] = {"Desmanche"},
        ["CarClube"] = {"Desmanche"},
        ["Virtude"] = {"Desmanche"},
        ["Big"] = {"Desmanche"},
        ["Outlaws"] = {"Desmanche"},
        ["Overdrive"] = {"Desmanche"},
    }
elseif cityName == "Caravelas" then
    farmGroupConfig = {        
        ["Banzas"] = {"Maconha"},        
        ["Sindicato"] = {"Maconha"},
        ["Laranjas"] = {"Maconha"},
        ["Gang8"] = {"Maconha"},
        ["Noxus"] =  {"Maconha"},        
        ["Gang7"] = {"Maconha"},
        ["LosAztecas"] = {"Maconha"},
        ["Barragem"] =  {"Maconha"},

        ["Vagos"] =  {"Metafetamina"},
        ["Luxor"] =  {"Metafetamina"},
        ["Overdrive"] = {"Metafetamina"},
        ["Gang6"] = {"Metafetamina"},
        ["LaMafia"] = {"Metafetamina"},        
        ["Umbrella"] = {"Metafetamina"},
        ["Afetados"] = {"Metafetamina"},
        ["Pinkmans"] = {"Metafetamina"},
        ["Hollywood"] = {"Metafetamina"},
        ["Amarelos"] = {"Metafetamina"},
        ["AlcateiaHsT"] = {"Metafetamina"},
        ["Callisto"] = {"Metafetamina"},
        ["Azuis"] = {"Metafetamina"},
        ["Cinzas"] = {"Metafetamina"},
        ["Vermelhos"] =  {"Metafetamina"},

        ["Verdes"] = {"Cocaina"},
        ["Gang9"] = {"Cocaina"},
        ["Brancos"] = {"Cocaina"},
        ["Rosas"] = {"Cocaina"},        
        ["Roxos"] = {"Cocaina"},
        ["DriftKing"] = {"Cocaina"},  
        
        ["Caribe"] = {"Lavagem"},
        ["Ballas"] =  {"Lavagem"},
        ["Metgala"] = {"Lavagem"},
        ["Bellagio"] = {"Lavagem"},        
        ["Tequilas"] = {"Lavagem"},
        ["Arcade"] = {"Lavagem"},        
        ["Bahamas"] = {"Lavagem"},        
        ["Redline"] = {"Lavagem"},
        ["Gang1"] =  {"Lavagem"},
        ["Putaria"] =  {"Lavagem"},

        ["Gang2"] =  {"Municao"},
        ["Tropadu7"] =  {"Municao"},
        ["Tribo"] = {"Municao"},
        ["Gang4"] = {"Municao"},
        ["Outlaws"] = {"Municao"},
        ["SonsofAnarchy"] = {"Municao"},
        ["Anonymous"] = {"Municao"},
        ["Fazendinha"] = {"Municao"},
        ["Campinho"] = {"Municao"},
        ["Gang3"] = {"Municao"},
        ["Morro-do-Sacola"] = {"Municao"},        
        ["Gang5"] = {"Municao"},
        ["Marrons"] = {"Municao"},        
        ["Warlocks"] = {"Municao"},
        ["Inglaterra"] = {"Municao"},
        ["Galaxy"] = {"Municao"},
        
        ["Dixavas"] = {"Armas"},
        ["Palazzo"] = {"Armas"},
        ["Mercenarios"] =  {"Armas"},        
        ["Franca"] = {"Armas"},
        ["Japao"] =  {"Armas"},
        ["Lavajato"] = {"Armas"},        
        -- ["Inglaterra"] =  {"Armas"},
        
        ["Gringa"] =  {"Armas"},
        ["Italia"] = {"Armas"},
        ["Russia"] = {"Armas"},
        ["Israel"] = {"Armas"},
        ["Playboy"] = {"Armas"},
        ["Mexico"] = {"Armas"},
        ["China"] = {"Armas"},
        
        ["TopGear"] = {"Desmanche"},
        ["Groove"] = {"Desmanche"},
        
        ["Bennys"] = {"Desmanche"},              
        ["FerroVelho"] = {"Desmanche"},
        ["Kraken"] = {"Desmanche"},
        ["CarClube"] = {"Desmanche"},
        ["Virtude"] = {"Desmanche"},
        ["Big"] = {"Desmanche"},
        ["Outlaws"] = {"Desmanche"},
    }
elseif cityName == "Kingdom" then
    farmGroupConfig = {
        ["Barragem"] =  {"Maconha"},
        ["Gang9"] =  {"Maconha"},
        ["Banzas"] = {"Maconha"},        
        ["Sindicato"] = {"Maconha"},
        ["Laranjas"] = {"Maconha"},
        ["Gang8"] = {"Maconha"},
        ["Noxus"] =  {"Maconha"},        
        ["Dixavas"] = {"Maconha"},        
        ["Gang7"] = {"Maconha"},

        ["Vagos"] =  {"Metafetamina"},
        ["LaMafia"] = {"Metafetamina"},        
        ["Umbrella"] = {"Metafetamina"},
        ["Afetados"] = {"Metafetamina"},
        ["Pinkmans"] = {"Metafetamina"},
        ["Hollywood"] = {"Metafetamina"},
        ["Amarelos"] = {"Metafetamina"},
        ["AlcateiaHsT"] = {"Metafetamina"},
        ["Callisto"] = {"Lavagem"},
        ["Azuis"] = {"Metafetamina"},
        ["Cinzas"] = {"Metafetamina"},
        ["Vermelhos"] =  {"Metafetamina"},

        ["Verdes"] = {"Cocaina"},
        ["Brancos"] = {"Cocaina"},
        ["Rosas"] = {"Cocaina"},
        ["Roxos"] = {"Cocaina"},

        ["Ballas"] =  {"Lavagem"},
        ["LosAztecas"] = {"Lavagem"},
        ["Metgala"] = {"Lavagem"},
        ["Bellagio"] = {"Lavagem"},        
        ["Tequilas"] = {"Lavagem"},
        ["Arcade"] = {"Lavagem"},        
        ["Bahamas"] = {"Lavagem"},
        ["Palazzo"] = {"Lavagem"},
        ["Luxor"] = {"Lavagem"},
        ["Redline"] = {"Lavagem"},
        ["Gang1"] =  {"Lavagem"},
        ["Putaria"] =  {"Lavagem"},

        ["Gang2"] =  {"Municao"},
        ["Tropadu7"] =  {"Municao"},
        ["Tribo"] = {"Municao"},
        ["Gang6"] = {"Municao"},
        ["Gang4"] = {"Municao"},
        ["Outlaws"] = {"Municao"},
        ["SonsofAnarchy"] = {"Municao"},
        ["Anonymous"] = {"Municao"},
        ["Fazendinha"] = {"Municao"},
        ["Campinho"] = {"Municao"},
        ["Gang3"] = {"Municao"},
        ["Morro-do-Sacola"] = {"Municao"},        
        ["Gang5"] = {"Municao"},
        ["Marrons"] = {"Municao"},        
        ["Warlocks"] = {"Municao"},
        ["Galaxy"] = {"Municao"},
        
        ["Inglaterra"] = {"Armas"},
        ["Mercenarios"] =  {"Armas"},
        ["Caribe"] = {"Armas"},
        ["Franca"] = {"Armas"},
        ["Japao"] =  {"Armas"},
        ["Lavajato"] = {"Armas"},
        -- ["Inglaterra"] =  {"Armas"},
        
        ["Gringa"] =  {"Armas"},
        ["Italia"] = {"Armas"},
        ["Russia"] = {"Armas"},
        ["Israel"] = {"Armas"},
        ["Playboy"] = {"Armas"},
        ["Mexico"] = {"Armas"},
        ["China"] = {"Armas"},
        
        ["TopGear"] = {"Desmanche"},
        ["Groove"] = {"Desmanche"},
        ["Overdrive"] = {"Desmanche"},
        ["Bennys"] = {"Desmanche"},
        ["DriftKing"] = {"Desmanche"},        
        ["FerroVelho"] = {"Desmanche"},
        ["Kraken"] = {"Desmanche"},
        ["CarClube"] = {"Desmanche"},
        ["Virtude"] = {"Desmanche"},
        ["Big"] = {"Desmanche"},
        ["Outlaws"] = {"Desmanche"},
    }
elseif cityName == "Universo" then
    farmGroupConfig = {
        ["Barragem"] =  {"Maconha"},
        ["Banzas"] = {"Maconha"},
        ["Dixavas"] = {"Maconha"},
        ["Sindicato"] = {"Maconha"},
        ["Laranjas"] = {"Maconha"},

        ["Vagos"] =  {"Metafetamina"},
        ["LaMafia"] = {"Metafetamina"},
        ["Umbrella"] = {"Metafetamina"},
        ["Metgala"] = {"Metafetamina"},
        ["Afetados"] = {"Metafetamina"},
        ["Pinkmans"] = {"Metafetamina"},
        ["Hollywood"] = {"Metafetamina"},
        ["Amarelos"] = {"Metafetamina"},
        ["AlcateiaHsT"] = {"Metafetamina"},

        ["Vermelhos"] =  {"Cocaina"},
        ["Verdes"] = {"Cocaina"},
        ["Gang9"] = {"Cocaina"},
        ["Brancos"] = {"Cocaina"},
        ["Rosas"] = {"Cocaina"},
        ["LosAztecas"] = {"Cocaina"},
        ["Roxos"] = {"Cocaina"},

        ["Ballas"] =  {"Lavagem"},
        ["Bellagio"] = {"Lavagem"},
        ["Lavajato"] = {"Lavagem"},
        ["Tequilas"] = {"Lavagem"},
        ["Arcade"] = {"Lavagem"},
        ["Callisto"] = {"Lavagem"},
        ["Bahamas"] = {"Lavagem"},
        ["Palazzo"] = {"Lavagem"},
        ["Luxor"] = {"Lavagem"},
        ["Redline"] = {"Lavagem"},

        ["Gang2"] =  {"Municao"},
        ["Tropadu7"] =  {"Municao"},
        ["Tribo"] = {"Municao"},
        ["Gang6"] = {"Municao"},
        ["Gang4"] = {"Municao"},
        ["Outlaws"] = {"Municao"},
        ["SonsofAnarchy"] = {"Municao"},
        ["Fazendinha"] = {"Municao"},
        ["Campinho"] = {"Municao"},
        ["Gang3"] = {"Municao"},
        ["Gang8"] = {"Municao"},
        ["Gang7"] = {"Municao"},
        ["Gang5"] = {"Municao"},    
        ["Anonymous"] = {"Municao"},
        ["Marrons"] = {"Municao"},
        ["Cinzas"] = {"Municao"},
        ["Azuis"] = {"Municao"},
        ["Warlocks"] = {"Municao"},
        ["Inglaterra"] = {"Municao"},
        ["Galaxy"] = {"Municao"},

        ["Gang1"] =  {"Armas"},
        ["Mercenarios"] =  {"Armas"},
        ["LosTugas"] =  {"Armas"},
        ["Caribe"] = {"Armas"},
        ["Franca"] = {"Armas"},
        ["Japao"] =  {"Armas"},
        -- ["Inglaterra"] =  {"Armas"},
        ["Noxus"] =  {"Armas"},
        ["Gringa"] =  {"Armas"},
        ["Italia"] = {"Armas"},
        ["Russia"] = {"Armas"},
        ["Israel"] = {"Armas"},
        ["Playboy"] = {"Armas"},
        ["Mexico"] = {"Armas"},
        ["China"] = {"Armas"},
        ["Jamakeikos"] =  {"Armas"},

        ["Groove"] = {"Desmanche"},
        ["Overdrive"] = {"Desmanche"},
        ["Bennys"] = {"Desmanche"},
        ["DriftKing"] = {"Desmanche"},        
        ["TopGear"] = {"Desmanche"},
        ["Kraken"] = {"Desmanche"},
        ["CarClube"] = {"Desmanche"},
        ["Virtude"] = {"Desmanche"},
        ["Big"] = {"Desmanche"},
        ["Outlaws"] = {"Desmanche"},
        ["Redline"] = {"Desmanche"},

    }
elseif cityName == "Maresia" then
    farmGroupConfig = {
        ["Barragem"] =  {"Maconha"},
        ["Banzas"] = {"Maconha"},
        ["Dixavas"] = {"Maconha"},
        ["Gang4"] = {"Maconha"},
        ["Sindicato"] = {"Maconha"},
        ["Laranjas"] = {"Maconha"},

        ["Vagos"] =  {"Metafetamina"},
        ["LaMafia"] = {"Metafetamina"},
        ["Umbrella"] = {"Metafetamina"},
        ["Metgala"] = {"Metafetamina"},
        ["Afetados"] = {"Metafetamina"},
        ["Pinkmans"] = {"Metafetamina"},
        ["Hollywood"] = {"Metafetamina"},
        ["Amarelos"] = {"Metafetamina"},
        ["AlcateiaHsT"] = {"Metafetamina"},

        ["Vermelhos"] =  {"Cocaina"},
        ["Verdes"] = {"Cocaina"},        
        ["Brancos"] = {"Cocaina"},
        ["Rosas"] = {"Cocaina"},
        ["LosAztecas"] = {"Cocaina"},
        ["Roxos"] = {"Cocaina"},

        ["Ballas"] =  {"Lavagem"},
        ["Bellagio"] = {"Lavagem"},
        ["Lavajato"] = {"Lavagem"},
        ["Tequilas"] = {"Lavagem"},
        ["Arcade"] = {"Lavagem"},
        ["Callisto"] = {"Lavagem"},
        ["Bahamas"] = {"Lavagem"},
        ["Palazzo"] = {"Lavagem"},
        ["Luxor"] = {"Lavagem"},
        ["Redline"] = {"Desmanche"},
        ["Gang2"] =  {"Municao"},
        ["Tropadu7"] =  {"Municao"},
        ["Tribo"] = {"Municao"},
        ["Gang6"] = {"Municao"},
        ["Gang4"] = {"Maconha"},
        ["Outlaws"] = {"Desmanche"},
        ["SonsofAnarchy"] = {"Municao"},
        ["Anonymous"] = {"Municao"},
        ["Fazendinha"] = {"Municao"},
        ["Campinho"] = {"Municao"},
        ["Gang3"] = {"Municao"},
        ["Gang8"] = {"Municao"},
        ["Gang7"] = {"Municao"},
        ["Morro-do-Sacola"] = {"Municao"},
        -- ["Gang5"] = {"Municao"},
        ["Marrons"] = {"Municao"},
        ["Cinzas"] = {"Municao"},
        ["Azuis"] = {"Municao"},
        ["Warlocks"] = {"Municao"},
        ["Inglaterra"] = {"Arma"},
        ["Galaxy"] = {"Municao"},

        ["Gang1"] =  {"Armas"},
        ["Jamakeikos"] =  {"Armas"},
        ["Mercenarios"] =  {"Armas"},
        ["Caribe"] = {"Armas"},
        ["Franca"] = {"Armas"},
        ["Japao"] =  {"Armas"},
        -- ["Inglaterra"] =  {"Armas"},
        ["Gang9"] = {"Armas"},
        ["Noxus"] =  {"Armas"},
        ["Gringa"] =  {"Armas"},
        ["Italia"] = {"Armas"},
        ["Russia"] = {"Armas"},
        ["Israel"] = {"Armas"},
        ["Playboy"] = {"Armas"},
        ["Mexico"] = {"Armas"},
        ["China"] = {"Armas"},

        ["Groove"] = {"Desmanche"},
        ["Overdrive"] = {"Desmanche"},
        ["Bennys"] = {"Desmanche"},
        ["DriftKing"] = {"Desmanche"},
        ["TopGear"] = {"Desmanche"},
        ["FerroVelho"] = {"Desmanche"},
        ["Kraken"] = {"Desmanche"},
        ["CarClube"] = {"Desmanche"},
        ["Virtude"] = {"Desmanche"},
        ["Big"] = {"Desmanche"},
        ["Outlaws"] = {"Desmanche"},
        ["Gang5"] = {"Municao"},
    }
elseif cityName == "Alexandria" then
    farmGroupConfig = {
        ["Barragem"] =  {"Maconha"},
        ["Dixavas"] = {"Maconha"},
        ["Gang4"] = {"Maconha"},
        ["Laranjas"] = {"Maconha"},
        ["Sindicato"] = {"Maconha"},
        ["Laranjas"] = {"Maconha"},

        ["Vagos"] =  {"Metafetamina"},
        ["Umbrella"] = {"Metafetamina"},
        ["Metgala"] = {"Metafetamina"},
        ["Afetados"] = {"Metafetamina"},
        ["Pinkmans"] = {"Metafetamina"},
        ["Hollywood"] = {"Metafetamina"},
        ["Amarelos"] = {"Metafetamina"},
        ["AlcateiaHsT"] = {"Metafetamina"},

        ["Vermelhos"] =  {"Cocaina"},
        ["LosAztecas"] = {"Cocaina"},
        ["Roxos"] = {"Cocaina"},
        ["Verdes"] = {"Cocaina"},
        ["Brancos"] = {"Cocaina"},

        ["Ballas"] =  {"Lavagem"},
        ["Bellagio"] = {"Lavagem"},
        ["Lavajato"] = {"Lavagem"},
        ["Tequilas"] = {"Lavagem"},
        ["Arcade"] = {"Lavagem"},
        ["Callisto"] = {"Lavagem"},
        ["Bahamas"] = {"Lavagem"},
        ["Palazzo"] = {"Lavagem"},
        ["Luxor"] = {"Lavagem"},

        ["Gang2"] =  {"Municao"},
        ["Gang9"] =  {"Municao"},
        ["Tropadu7"] =  {"Municao"},
        ["Tribo"] = {"Municao"},
        ["Gang6"] = {"Municao"},
        ["Outlaws"] = {"Municao"},
        ["SonsofAnarchy"] = {"Municao"},
        ["Fazendinha"] = {"Municao"},
        ["Campinho"] = {"Municao"},
        ["Gang3"] = {"Municao"},
        ["Gang8"] = {"Municao"},
        ["Gang7"] = {"Municao"},
        ["Gang5"] = {"Municao"},
        ["Marrons"] = {"Municao"},
        ["Cinzas"] = {"Municao"},
        ["Azuis"] = {"Municao"},
        ["Warlocks"] = {"Municao"},
        ["Anonymous"] = {"Municao"},

        ["Gang1"] =  {"Armas"},
        ["Rosas"] = {"Armas"},
        ["Mercenarios"] =  {"Armas"},
        ["Caribe"] = {"Armas"},
        ["Franca"] = {"Armas"},
        ["Japao"] =  {"Armas"},
        ["Inglaterra"] =  {"Armas"},
        ["Noxus"] =  {"Armas"},
        ["LaMafia"] =  {"Armas"},
        ["Gringa"] =  {"Armas"},
        ["Italia"] = {"Armas"},
        ["Russia"] = {"Armas"},
        ["Israel"] = {"Armas"},
        ["Playboy"] = {"Armas"},
        ["Mexico"] = {"Armas"},
        ["China"] = {"Armas"},
        
        ["Groove"] = {"Desmanche"},
        ["Overdrive"] = {"Desmanche"},
        ["Bennys"] = {"Desmanche"},
        ["DriftKing"] = {"Desmanche"},
        ["TopGear"] = {"Desmanche"},
        ["FerroVelho"] = {"Desmanche"},
        ["CarClube"] = {"Desmanche"},
        ["Virtude"] = {"Desmanche"},
        ["Kraken"] = {"Desmanche"},
        ["Big"] = {"Desmanche"},
        ["Outlaws"] = {"Desmanche"},
        ["Redline"] = {"Desmanche"},

    }
end

function GetGroupType(Group)
    return farmGroupConfig[Group]
end
exports("GetGroupType", GetGroupType)

function GetTypeFarm(Type)
    return farmConfig[Type]
end
exports("GetTypeFarm", GetTypeFarm)